begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|editor
operator|.
name|validation
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|validation
operator|.
name|SimpleValidationFailure
import|;
end_import

begin_comment
comment|/**  *  ValidationFailure implementation that described a failure of attribute.  */
end_comment

begin_class
specifier|public
class|class
name|AttributeValidationFailure
extends|extends
name|SimpleValidationFailure
block|{
specifier|public
name|AttributeValidationFailure
parameter_list|(
name|int
name|columnIndex
parameter_list|,
name|String
name|error
parameter_list|)
block|{
name|super
argument_list|(
name|columnIndex
argument_list|,
name|error
argument_list|)
expr_stmt|;
block|}
specifier|public
name|int
name|getColumnIndex
parameter_list|()
block|{
return|return
operator|(
name|Integer
operator|)
name|source
return|;
block|}
block|}
end_class

end_unit

