begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|project2
operator|.
name|validate
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|DataChannelDescriptor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|DataNodeDescriptor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|DataMap
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|util
operator|.
name|Util
import|;
end_import

begin_class
class|class
name|DataMapValidator
block|{
name|void
name|validate
parameter_list|(
name|Object
name|object
parameter_list|,
name|ConfigurationValidator
name|configurationValidator
parameter_list|)
block|{
name|DataMap
name|map
init|=
operator|(
name|DataMap
operator|)
name|object
decl_stmt|;
name|validateName
argument_list|(
name|map
argument_list|,
name|object
argument_list|,
name|configurationValidator
argument_list|)
expr_stmt|;
comment|// check if data map is not attached to any nodes
name|validateNodeLinks
argument_list|(
name|map
argument_list|,
name|object
argument_list|,
name|configurationValidator
argument_list|)
expr_stmt|;
block|}
name|void
name|validateNodeLinks
parameter_list|(
name|DataMap
name|map
parameter_list|,
name|Object
name|object
parameter_list|,
name|ConfigurationValidator
name|validator
parameter_list|)
block|{
name|DataChannelDescriptor
name|domain
init|=
operator|(
name|DataChannelDescriptor
operator|)
name|validator
operator|.
name|getProject
argument_list|()
operator|.
name|getRootNode
argument_list|()
decl_stmt|;
if|if
condition|(
name|domain
operator|==
literal|null
condition|)
block|{
return|return;
block|}
name|boolean
name|unlinked
init|=
literal|true
decl_stmt|;
name|int
name|nodeCount
init|=
literal|0
decl_stmt|;
for|for
control|(
specifier|final
name|DataNodeDescriptor
name|node
range|:
name|domain
operator|.
name|getNodeDescriptors
argument_list|()
control|)
block|{
name|nodeCount
operator|++
expr_stmt|;
if|if
condition|(
name|node
operator|.
name|getDataMapNames
argument_list|()
operator|.
name|contains
argument_list|(
name|map
operator|.
name|getName
argument_list|()
argument_list|)
condition|)
block|{
name|unlinked
operator|=
literal|false
expr_stmt|;
break|break;
block|}
block|}
if|if
condition|(
name|unlinked
operator|&&
name|nodeCount
operator|>
literal|0
condition|)
block|{
name|validator
operator|.
name|registerWarning
argument_list|(
literal|"DataMap is not linked to any DataNodes."
argument_list|,
name|object
argument_list|)
expr_stmt|;
block|}
block|}
name|void
name|validateName
parameter_list|(
name|DataMap
name|map
parameter_list|,
name|Object
name|object
parameter_list|,
name|ConfigurationValidator
name|validator
parameter_list|)
block|{
name|String
name|name
init|=
name|map
operator|.
name|getName
argument_list|()
decl_stmt|;
if|if
condition|(
name|Util
operator|.
name|isEmptyString
argument_list|(
name|name
argument_list|)
condition|)
block|{
name|validator
operator|.
name|registerError
argument_list|(
literal|"Unnamed DataMap."
argument_list|,
name|object
argument_list|)
expr_stmt|;
return|return;
block|}
name|DataChannelDescriptor
name|domain
init|=
operator|(
name|DataChannelDescriptor
operator|)
name|validator
operator|.
name|getProject
argument_list|()
operator|.
name|getRootNode
argument_list|()
decl_stmt|;
if|if
condition|(
name|domain
operator|==
literal|null
condition|)
block|{
return|return;
block|}
comment|// check for duplicate names in the parent context
for|for
control|(
specifier|final
name|DataMap
name|otherMap
range|:
name|domain
operator|.
name|getDataMaps
argument_list|()
control|)
block|{
if|if
condition|(
name|otherMap
operator|==
name|map
condition|)
block|{
continue|continue;
block|}
if|if
condition|(
name|name
operator|.
name|equals
argument_list|(
name|otherMap
operator|.
name|getName
argument_list|()
argument_list|)
condition|)
block|{
name|validator
operator|.
name|registerError
argument_list|(
literal|"Duplicate DataMap name: "
operator|+
name|name
operator|+
literal|"."
argument_list|,
name|object
argument_list|)
expr_stmt|;
return|return;
block|}
block|}
block|}
block|}
end_class

end_unit

