begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|project2
operator|.
name|validate
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|conf
operator|.
name|DriverDataSourceFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|DataChannelDescriptor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|DataNodeDescriptor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|util
operator|.
name|Util
import|;
end_import

begin_class
class|class
name|DataNodeValidator
block|{
name|void
name|validate
parameter_list|(
name|Object
name|object
parameter_list|,
name|ConfigurationValidator
name|configurationValidator
parameter_list|)
block|{
name|DataNodeDescriptor
name|node
init|=
operator|(
name|DataNodeDescriptor
operator|)
name|object
decl_stmt|;
name|validateName
argument_list|(
name|node
argument_list|,
name|object
argument_list|,
name|configurationValidator
argument_list|)
expr_stmt|;
name|validateConnection
argument_list|(
name|node
argument_list|,
name|object
argument_list|,
name|configurationValidator
argument_list|)
expr_stmt|;
block|}
name|void
name|validateConnection
parameter_list|(
name|DataNodeDescriptor
name|node
parameter_list|,
name|Object
name|object
parameter_list|,
name|ConfigurationValidator
name|validator
parameter_list|)
block|{
name|String
name|factory
init|=
name|node
operator|.
name|getDataSourceFactoryType
argument_list|()
decl_stmt|;
comment|// If direct factory, make sure the location is a valid file name.
if|if
condition|(
name|Util
operator|.
name|isEmptyString
argument_list|(
name|factory
argument_list|)
condition|)
block|{
name|validator
operator|.
name|registerError
argument_list|(
literal|"No DataSource factory."
argument_list|,
name|object
argument_list|)
expr_stmt|;
block|}
if|else if
condition|(
operator|!
name|DriverDataSourceFactory
operator|.
name|class
operator|.
name|getName
argument_list|()
operator|.
name|equals
argument_list|(
name|factory
argument_list|)
condition|)
block|{
name|String
name|location
init|=
name|node
operator|.
name|getParameters
argument_list|()
decl_stmt|;
if|if
condition|(
name|Util
operator|.
name|isEmptyString
argument_list|(
name|location
argument_list|)
condition|)
block|{
name|validator
operator|.
name|registerError
argument_list|(
literal|"DataNode has no location parameter."
argument_list|,
name|object
argument_list|)
expr_stmt|;
block|}
block|}
block|}
name|void
name|validateName
parameter_list|(
name|DataNodeDescriptor
name|node
parameter_list|,
name|Object
name|object
parameter_list|,
name|ConfigurationValidator
name|validator
parameter_list|)
block|{
name|String
name|name
init|=
name|node
operator|.
name|getName
argument_list|()
decl_stmt|;
if|if
condition|(
name|Util
operator|.
name|isEmptyString
argument_list|(
name|name
argument_list|)
condition|)
block|{
name|validator
operator|.
name|registerError
argument_list|(
literal|"Unnamed DataNode."
argument_list|,
name|object
argument_list|)
expr_stmt|;
return|return;
block|}
name|DataChannelDescriptor
name|dataChannelDescriptor
init|=
operator|(
name|DataChannelDescriptor
operator|)
name|validator
operator|.
name|getProject
argument_list|()
operator|.
name|getRootNode
argument_list|()
decl_stmt|;
comment|// check for duplicate names in the parent context
for|for
control|(
specifier|final
name|DataNodeDescriptor
name|otherNode
range|:
name|dataChannelDescriptor
operator|.
name|getNodeDescriptors
argument_list|()
control|)
block|{
if|if
condition|(
name|otherNode
operator|==
name|node
condition|)
block|{
continue|continue;
block|}
if|if
condition|(
name|name
operator|.
name|equals
argument_list|(
name|otherNode
operator|.
name|getName
argument_list|()
argument_list|)
condition|)
block|{
name|validator
operator|.
name|registerError
argument_list|(
literal|"Duplicate DataNode name: "
operator|+
name|name
operator|+
literal|"."
argument_list|,
name|object
argument_list|)
expr_stmt|;
break|break;
block|}
block|}
block|}
block|}
end_class

end_unit

