begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|jpa
operator|.
name|entity
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|DiscriminatorColumn
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|DiscriminatorType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|DiscriminatorValue
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|Entity
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|Inheritance
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|InheritanceType
import|;
end_import

begin_class
annotation|@
name|Inheritance
argument_list|(
name|strategy
operator|=
name|InheritanceType
operator|.
name|SINGLE_TABLE
argument_list|)
annotation|@
name|Entity
argument_list|(
name|name
operator|=
literal|"MockEntity3"
argument_list|)
annotation|@
name|DiscriminatorColumn
argument_list|(
name|name
operator|=
literal|"column1"
argument_list|,
name|discriminatorType
operator|=
name|DiscriminatorType
operator|.
name|CHAR
argument_list|,
name|columnDefinition
operator|=
literal|"count(1)"
argument_list|,
name|length
operator|=
literal|5
argument_list|)
annotation|@
name|DiscriminatorValue
argument_list|(
name|value
operator|=
literal|"DV"
argument_list|)
specifier|public
class|class
name|MockEntity3
block|{  }
end_class

end_unit

