begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|jpa
operator|.
name|entity
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|EntityListeners
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|ExcludeDefaultListeners
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|ExcludeSuperclassListeners
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|IdClass
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|MappedSuperclass
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|PostLoad
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|PostPersist
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|PostRemove
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|PostUpdate
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|PrePersist
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|PreRemove
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|PreUpdate
import|;
end_import

begin_class
annotation|@
name|MappedSuperclass
annotation|@
name|IdClass
argument_list|(
name|MockIdClass
operator|.
name|class
argument_list|)
annotation|@
name|ExcludeDefaultListeners
annotation|@
name|ExcludeSuperclassListeners
annotation|@
name|EntityListeners
argument_list|(
name|value
operator|=
block|{
name|MockEntityListener1
operator|.
name|class
block|}
argument_list|)
specifier|public
class|class
name|MockMappedSuperclass1
block|{
annotation|@
name|PrePersist
specifier|protected
name|void
name|eprePersist
parameter_list|()
block|{
block|}
annotation|@
name|PostPersist
specifier|protected
name|void
name|epostPersist
parameter_list|()
block|{
block|}
annotation|@
name|PreRemove
specifier|protected
name|void
name|epreRemove
parameter_list|()
block|{
block|}
annotation|@
name|PostRemove
specifier|protected
name|void
name|epostRemove
parameter_list|()
block|{
block|}
annotation|@
name|PreUpdate
specifier|protected
name|void
name|epreUpdate
parameter_list|()
block|{
block|}
annotation|@
name|PostUpdate
specifier|protected
name|void
name|epostUpdate
parameter_list|()
block|{
block|}
annotation|@
name|PostLoad
specifier|protected
name|void
name|epostLoad
parameter_list|()
block|{
block|}
block|}
end_class

end_unit

