begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|jcache
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|cache
operator|.
name|processor
operator|.
name|EntryProcessor
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|cache
operator|.
name|processor
operator|.
name|EntryProcessorException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|cache
operator|.
name|processor
operator|.
name|MutableEntry
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|CayenneRuntimeException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|cache
operator|.
name|QueryCacheEntryFactory
import|;
end_import

begin_comment
comment|/**  * @since 4.0  */
end_comment

begin_class
specifier|public
class|class
name|JCacheEntryLoader
implements|implements
name|EntryProcessor
argument_list|<
name|String
argument_list|,
name|List
argument_list|,
name|List
argument_list|>
block|{
specifier|private
name|QueryCacheEntryFactory
name|entryFactory
decl_stmt|;
specifier|public
name|JCacheEntryLoader
parameter_list|(
name|QueryCacheEntryFactory
name|entryFactory
parameter_list|)
block|{
name|this
operator|.
name|entryFactory
operator|=
name|entryFactory
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|List
name|process
parameter_list|(
name|MutableEntry
argument_list|<
name|String
argument_list|,
name|List
argument_list|>
name|entry
parameter_list|,
name|Object
modifier|...
name|arguments
parameter_list|)
throws|throws
name|EntryProcessorException
block|{
if|if
condition|(
operator|!
name|entry
operator|.
name|exists
argument_list|()
condition|)
block|{
name|List
name|result
init|=
operator|(
name|List
operator|)
name|entryFactory
operator|.
name|createObject
argument_list|()
decl_stmt|;
comment|// sanity checking value
if|if
condition|(
name|result
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|CayenneRuntimeException
argument_list|(
literal|"Null object created: "
operator|+
name|entry
operator|.
name|getKey
argument_list|()
argument_list|)
throw|;
block|}
name|entry
operator|.
name|setValue
argument_list|(
name|result
argument_list|)
expr_stmt|;
block|}
return|return
name|entry
operator|.
name|getValue
argument_list|()
return|;
block|}
block|}
end_class

end_unit

