begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|rop
operator|.
name|client
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|CayenneRuntime
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|di
operator|.
name|Module
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|remote
operator|.
name|ClientConnection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import static
name|java
operator|.
name|util
operator|.
name|Arrays
operator|.
name|asList
import|;
end_import

begin_comment
comment|/**  * A user application entry point to Cayenne stack on the ROP client.  *   * @since 3.1  */
end_comment

begin_comment
comment|// TODO: module auto-loading and ClientRuntimeBuilder
end_comment

begin_class
specifier|public
class|class
name|ClientRuntime
extends|extends
name|CayenneRuntime
block|{
specifier|private
specifier|static
name|Collection
argument_list|<
name|Module
argument_list|>
name|collectModules
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|properties
parameter_list|,
name|Module
modifier|...
name|extraModules
parameter_list|)
block|{
name|Collection
argument_list|<
name|Module
argument_list|>
name|modules
init|=
name|extraModules
operator|!=
literal|null
condition|?
name|asList
argument_list|(
name|extraModules
argument_list|)
else|:
name|Collections
operator|.
expr|<
name|Module
operator|>
name|emptyList
argument_list|()
decl_stmt|;
return|return
name|collectModules
argument_list|(
name|properties
argument_list|,
name|modules
argument_list|)
return|;
block|}
specifier|private
specifier|static
name|Collection
argument_list|<
name|Module
argument_list|>
name|collectModules
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|properties
parameter_list|,
name|Collection
argument_list|<
name|Module
argument_list|>
name|extraModules
parameter_list|)
block|{
name|Collection
argument_list|<
name|Module
argument_list|>
name|modules
init|=
operator|new
name|ArrayList
argument_list|<>
argument_list|()
decl_stmt|;
name|modules
operator|.
name|add
argument_list|(
operator|new
name|ClientModule
argument_list|(
name|properties
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|extraModules
operator|!=
literal|null
condition|)
block|{
name|modules
operator|.
name|addAll
argument_list|(
name|extraModules
argument_list|)
expr_stmt|;
block|}
return|return
name|modules
return|;
block|}
comment|/** 	 * Creates a client runtime configuring it with a standard set of services 	 * contained in {@link ClientModule}. CayenneClientModule is created based 	 * on a set of properties that contain things like connection information, 	 * etc. Recognized property keys are defined in {@link ClientModule}. An 	 * optional array of extra modules may contain service overrides and/or user 	 * services. 	 */
specifier|public
name|ClientRuntime
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|properties
parameter_list|,
name|Collection
argument_list|<
name|Module
argument_list|>
name|extraModules
parameter_list|)
block|{
name|this
argument_list|(
name|collectModules
argument_list|(
name|properties
argument_list|,
name|extraModules
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/** 	 * Creates a client runtime configuring it with a standard set of services 	 * contained in {@link ClientModule}. CayenneClientModule is created based 	 * on a set of properties that contain things like connection information, 	 * etc. Recognized property keys are defined in {@link ClientModule}. An 	 * optional collection of extra modules may contain service overrides and/or 	 * user services. 	 */
specifier|public
name|ClientRuntime
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|properties
parameter_list|,
name|Module
modifier|...
name|extraModules
parameter_list|)
block|{
name|this
argument_list|(
name|collectModules
argument_list|(
name|properties
argument_list|,
name|extraModules
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/** 	 * @since 4.0 	 */
specifier|protected
name|ClientRuntime
parameter_list|(
name|Collection
argument_list|<
name|Module
argument_list|>
name|modules
parameter_list|)
block|{
name|super
argument_list|(
name|modules
argument_list|)
expr_stmt|;
block|}
specifier|public
name|ClientConnection
name|getConnection
parameter_list|()
block|{
return|return
name|injector
operator|.
name|getInstance
argument_list|(
name|ClientConnection
operator|.
name|class
argument_list|)
return|;
block|}
block|}
end_class

end_unit

