begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|rop
operator|.
name|client
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|ConfigurationException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|DataChannel
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|Constants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|RuntimeProperties
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|di
operator|.
name|Inject
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|di
operator|.
name|Provider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|event
operator|.
name|EventManager
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|remote
operator|.
name|ClientChannel
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|remote
operator|.
name|ClientConnection
import|;
end_import

begin_class
specifier|public
class|class
name|ClientChannelProvider
implements|implements
name|Provider
argument_list|<
name|DataChannel
argument_list|>
block|{
annotation|@
name|Inject
specifier|protected
name|ClientConnection
name|connection
decl_stmt|;
annotation|@
name|Inject
specifier|protected
name|EventManager
name|eventManager
decl_stmt|;
annotation|@
name|Inject
specifier|protected
name|RuntimeProperties
name|properties
decl_stmt|;
specifier|public
name|DataChannel
name|get
parameter_list|()
throws|throws
name|ConfigurationException
block|{
name|boolean
name|channelEvents
init|=
name|properties
operator|.
name|getBoolean
argument_list|(
name|ClientConstants
operator|.
name|ROP_CHANNEL_EVENTS_PROPERTY
argument_list|,
literal|false
argument_list|)
decl_stmt|;
return|return
operator|new
name|ClientChannel
argument_list|(
name|connection
argument_list|,
name|channelEvents
argument_list|,
name|eventManager
argument_list|,
name|channelEvents
argument_list|)
return|;
block|}
block|}
end_class

end_unit

