begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|crypto
operator|.
name|batch
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|access
operator|.
name|translator
operator|.
name|batch
operator|.
name|BatchParameterBinding
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|access
operator|.
name|translator
operator|.
name|batch
operator|.
name|BatchTranslator
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|access
operator|.
name|translator
operator|.
name|batch
operator|.
name|BatchTranslatorFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|crypto
operator|.
name|cipher
operator|.
name|CipherService
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|crypto
operator|.
name|map
operator|.
name|ColumnMapper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|dba
operator|.
name|DbAdapter
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|di
operator|.
name|Inject
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|query
operator|.
name|BatchQuery
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|query
operator|.
name|BatchQueryRow
import|;
end_import

begin_comment
comment|/**  * @since 3.2  */
end_comment

begin_class
specifier|public
class|class
name|CryptoBatchTranslatorFactoryDecorator
implements|implements
name|BatchTranslatorFactory
block|{
specifier|private
name|CipherService
name|cipherService
decl_stmt|;
specifier|private
name|ColumnMapper
name|columnMapper
decl_stmt|;
specifier|private
name|BatchTranslatorFactory
name|delegate
decl_stmt|;
specifier|public
name|CryptoBatchTranslatorFactoryDecorator
parameter_list|(
annotation|@
name|Inject
name|BatchTranslatorFactory
name|delegate
parameter_list|,
annotation|@
name|Inject
name|CipherService
name|cipherService
parameter_list|,
annotation|@
name|Inject
name|ColumnMapper
name|columnMapper
parameter_list|)
block|{
name|this
operator|.
name|columnMapper
operator|=
name|columnMapper
expr_stmt|;
name|this
operator|.
name|cipherService
operator|=
name|cipherService
expr_stmt|;
name|this
operator|.
name|delegate
operator|=
name|delegate
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|BatchTranslator
name|translator
parameter_list|(
name|BatchQuery
name|query
parameter_list|,
name|DbAdapter
name|adapter
parameter_list|,
name|String
name|trimFunction
parameter_list|)
block|{
specifier|final
name|BatchTranslator
name|delegateTranslator
init|=
name|delegate
operator|.
name|translator
argument_list|(
name|query
argument_list|,
name|adapter
argument_list|,
name|trimFunction
argument_list|)
decl_stmt|;
return|return
operator|new
name|BatchTranslator
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|String
name|getTrimFunction
parameter_list|()
block|{
return|return
name|delegateTranslator
operator|.
name|getTrimFunction
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|createSqlString
parameter_list|()
throws|throws
name|IOException
block|{
return|return
name|delegateTranslator
operator|.
name|createSqlString
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|List
argument_list|<
name|BatchParameterBinding
argument_list|>
name|createBindings
parameter_list|(
name|BatchQueryRow
name|row
parameter_list|)
block|{
name|List
argument_list|<
name|BatchParameterBinding
argument_list|>
name|bindings
init|=
name|delegateTranslator
operator|.
name|createBindings
argument_list|(
name|row
argument_list|)
decl_stmt|;
for|for
control|(
name|BatchParameterBinding
name|b
range|:
name|bindings
control|)
block|{
if|if
condition|(
name|columnMapper
operator|.
name|isEncrypted
argument_list|(
name|b
operator|.
name|getAttribute
argument_list|()
argument_list|)
condition|)
block|{
name|Object
name|encrypted
init|=
name|cipherService
operator|.
name|encrypt
argument_list|(
name|b
operator|.
name|getValue
argument_list|()
argument_list|,
name|b
operator|.
name|getAttribute
argument_list|()
operator|.
name|getType
argument_list|()
argument_list|)
decl_stmt|;
name|b
operator|.
name|setValue
argument_list|(
name|encrypted
argument_list|)
expr_stmt|;
block|}
block|}
return|return
name|bindings
return|;
block|}
block|}
return|;
block|}
block|}
end_class

end_unit

