begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|access
operator|.
name|flush
operator|.
name|operation
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|ObjectId
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|PersistenceState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|Persistent
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|DbAttribute
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|DbEntity
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|*
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|mockito
operator|.
name|Mockito
operator|.
name|mock
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|mockito
operator|.
name|Mockito
operator|.
name|when
import|;
end_import

begin_comment
comment|/**  * @since 4.2  */
end_comment

begin_class
specifier|public
class|class
name|ValuesTest
block|{
annotation|@
name|Test
specifier|public
name|void
name|testEmptyValues
parameter_list|()
block|{
name|ObjectId
name|id
init|=
name|ObjectId
operator|.
name|of
argument_list|(
literal|"test"
argument_list|,
literal|"id"
argument_list|,
literal|123
argument_list|)
decl_stmt|;
name|Persistent
name|persistent
init|=
name|mockObject
argument_list|(
name|id
argument_list|)
decl_stmt|;
name|DbRowOp
name|row
init|=
name|mockRow
argument_list|(
name|persistent
argument_list|)
decl_stmt|;
name|Values
name|values
init|=
operator|new
name|Values
argument_list|(
name|row
argument_list|,
literal|false
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
name|values
operator|.
name|getUpdatedAttributes
argument_list|()
operator|.
name|isEmpty
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|values
operator|.
name|getSnapshot
argument_list|()
operator|.
name|isEmpty
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|values
operator|.
name|getFlattenedIds
argument_list|()
operator|.
name|isEmpty
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|values
operator|.
name|isEmpty
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testValuesWithId
parameter_list|()
block|{
name|ObjectId
name|id
init|=
name|ObjectId
operator|.
name|of
argument_list|(
literal|"test"
argument_list|,
literal|"id"
argument_list|,
literal|123
argument_list|)
decl_stmt|;
name|Persistent
name|persistent
init|=
name|mockObject
argument_list|(
name|id
argument_list|)
decl_stmt|;
name|DbRowOp
name|row
init|=
name|mockRow
argument_list|(
name|persistent
argument_list|)
decl_stmt|;
name|Values
name|values
init|=
operator|new
name|Values
argument_list|(
name|row
argument_list|,
literal|true
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
name|values
operator|.
name|getUpdatedAttributes
argument_list|()
operator|.
name|isEmpty
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|values
operator|.
name|getFlattenedIds
argument_list|()
operator|.
name|isEmpty
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|Collections
operator|.
name|singletonMap
argument_list|(
literal|"id"
argument_list|,
literal|123
argument_list|)
argument_list|,
name|values
operator|.
name|getSnapshot
argument_list|()
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|values
operator|.
name|isEmpty
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testValuesWithUpdatedAttributes
parameter_list|()
block|{
name|ObjectId
name|id
init|=
name|ObjectId
operator|.
name|of
argument_list|(
literal|"test"
argument_list|,
literal|"id"
argument_list|,
literal|123
argument_list|)
decl_stmt|;
name|Persistent
name|persistent
init|=
name|mockObject
argument_list|(
name|id
argument_list|)
decl_stmt|;
name|DbRowOp
name|row
init|=
name|mockRow
argument_list|(
name|persistent
argument_list|)
decl_stmt|;
name|Values
name|values
init|=
operator|new
name|Values
argument_list|(
name|row
argument_list|,
literal|false
argument_list|)
decl_stmt|;
name|DbAttribute
name|attr1
init|=
operator|new
name|DbAttribute
argument_list|(
literal|"attr1"
argument_list|)
decl_stmt|;
name|values
operator|.
name|addValue
argument_list|(
name|attr1
argument_list|,
literal|32
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|Collections
operator|.
name|singletonList
argument_list|(
name|attr1
argument_list|)
argument_list|,
name|values
operator|.
name|getUpdatedAttributes
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|Collections
operator|.
name|singletonMap
argument_list|(
literal|"attr1"
argument_list|,
literal|32
argument_list|)
argument_list|,
name|values
operator|.
name|getSnapshot
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|values
operator|.
name|getFlattenedIds
argument_list|()
operator|.
name|isEmpty
argument_list|()
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|values
operator|.
name|isEmpty
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|private
name|DbRowOp
name|mockRow
parameter_list|(
name|Persistent
name|persistent
parameter_list|)
block|{
name|DbRowOp
name|row
init|=
name|mock
argument_list|(
name|DbRowOp
operator|.
name|class
argument_list|)
decl_stmt|;
name|ObjectId
name|objectId
init|=
name|persistent
operator|.
name|getObjectId
argument_list|()
decl_stmt|;
name|when
argument_list|(
name|row
operator|.
name|getChangeId
argument_list|()
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|objectId
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|row
operator|.
name|getObject
argument_list|()
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|persistent
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|row
operator|.
name|getEntity
argument_list|()
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|mockEntity
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|row
return|;
block|}
specifier|private
name|Persistent
name|mockObject
parameter_list|(
name|ObjectId
name|id
parameter_list|)
block|{
name|Persistent
name|persistent
init|=
name|mock
argument_list|(
name|Persistent
operator|.
name|class
argument_list|)
decl_stmt|;
name|when
argument_list|(
name|persistent
operator|.
name|getObjectId
argument_list|()
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|id
argument_list|)
expr_stmt|;
name|when
argument_list|(
name|persistent
operator|.
name|getPersistenceState
argument_list|()
argument_list|)
operator|.
name|thenReturn
argument_list|(
name|PersistenceState
operator|.
name|MODIFIED
argument_list|)
expr_stmt|;
return|return
name|persistent
return|;
block|}
specifier|private
name|DbEntity
name|mockEntity
parameter_list|()
block|{
name|DbAttribute
name|attribute1
init|=
operator|new
name|DbAttribute
argument_list|(
literal|"id"
argument_list|)
decl_stmt|;
name|attribute1
operator|.
name|setPrimaryKey
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|DbAttribute
name|attribute2
init|=
operator|new
name|DbAttribute
argument_list|(
literal|"attr"
argument_list|)
decl_stmt|;
name|DbEntity
name|testEntity
init|=
operator|new
name|DbEntity
argument_list|(
literal|"TEST"
argument_list|)
decl_stmt|;
name|testEntity
operator|.
name|addAttribute
argument_list|(
name|attribute1
argument_list|)
expr_stmt|;
name|testEntity
operator|.
name|addAttribute
argument_list|(
name|attribute2
argument_list|)
expr_stmt|;
return|return
name|testEntity
return|;
block|}
block|}
end_class

end_unit

