begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|CayenneRuntimeException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|ObjectId
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|Persistent
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|collections
operator|.
name|collection
operator|.
name|CompositeCollection
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_comment
comment|/**  * @since 4.0  */
end_comment

begin_class
class|class
name|MappingCache
implements|implements
name|MappingNamespace
block|{
specifier|private
specifier|static
specifier|final
name|ObjEntity
name|OBJ_DUPLICATE_MARKER
init|=
operator|new
name|ObjEntity
argument_list|()
decl_stmt|;
specifier|protected
specifier|static
specifier|final
name|Logger
name|logger
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|MappingCache
operator|.
name|class
argument_list|)
decl_stmt|;
specifier|protected
name|Collection
argument_list|<
name|DataMap
argument_list|>
name|maps
decl_stmt|;
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|QueryDescriptor
argument_list|>
name|queryDesriptors
decl_stmt|;
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|Embeddable
argument_list|>
name|embeddables
decl_stmt|;
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|SQLResult
argument_list|>
name|results
decl_stmt|;
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|DbEntity
argument_list|>
name|dbEntities
decl_stmt|;
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|ObjEntity
argument_list|>
name|objEntities
decl_stmt|;
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|ObjEntity
argument_list|>
name|objEntitiesByClassName
decl_stmt|;
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|Procedure
argument_list|>
name|procedures
decl_stmt|;
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|EntityInheritanceTree
argument_list|>
name|entityInheritanceCache
decl_stmt|;
name|MappingCache
parameter_list|(
name|Collection
argument_list|<
name|DataMap
argument_list|>
name|maps
parameter_list|)
block|{
name|this
operator|.
name|maps
operator|=
name|maps
expr_stmt|;
name|this
operator|.
name|embeddables
operator|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
expr_stmt|;
name|this
operator|.
name|queryDesriptors
operator|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
expr_stmt|;
name|this
operator|.
name|dbEntities
operator|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
expr_stmt|;
name|this
operator|.
name|objEntities
operator|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
expr_stmt|;
name|this
operator|.
name|objEntitiesByClassName
operator|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
expr_stmt|;
name|this
operator|.
name|procedures
operator|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
expr_stmt|;
name|this
operator|.
name|entityInheritanceCache
operator|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
expr_stmt|;
name|this
operator|.
name|results
operator|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
expr_stmt|;
name|index
argument_list|()
expr_stmt|;
block|}
specifier|private
name|void
name|index
parameter_list|()
block|{
comment|// index DbEntities separately and before ObjEntities to avoid infinite
comment|// loops when looking up DbEntities during ObjEntity index op
for|for
control|(
name|DataMap
name|map
range|:
name|maps
control|)
block|{
name|dbEntities
operator|.
name|putAll
argument_list|(
name|map
operator|.
name|getDbEntityMap
argument_list|()
argument_list|)
expr_stmt|;
block|}
for|for
control|(
name|DataMap
name|map
range|:
name|maps
control|)
block|{
comment|// index ObjEntities by name
name|objEntities
operator|.
name|putAll
argument_list|(
name|map
operator|.
name|getObjEntityMap
argument_list|()
argument_list|)
expr_stmt|;
comment|// index ObjEntities by class name
for|for
control|(
name|ObjEntity
name|oe
range|:
name|map
operator|.
name|getObjEntities
argument_list|()
control|)
block|{
comment|// use class name as a key to avoid class loading here...
name|String
name|className
init|=
name|oe
operator|.
name|getJavaClassName
argument_list|()
decl_stmt|;
if|if
condition|(
name|className
operator|==
literal|null
condition|)
block|{
continue|continue;
block|}
comment|// allow duplicates, but put a special marker indicating
comment|// that this entity can't be looked up by class
name|Object
name|existing
init|=
name|objEntitiesByClassName
operator|.
name|get
argument_list|(
name|className
argument_list|)
decl_stmt|;
if|if
condition|(
name|existing
operator|!=
literal|null
operator|&&
name|existing
operator|!=
name|OBJ_DUPLICATE_MARKER
condition|)
block|{
name|objEntitiesByClassName
operator|.
name|put
argument_list|(
name|className
argument_list|,
name|OBJ_DUPLICATE_MARKER
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|objEntitiesByClassName
operator|.
name|put
argument_list|(
name|className
argument_list|,
name|oe
argument_list|)
expr_stmt|;
block|}
block|}
comment|// index stored procedures
name|procedures
operator|.
name|putAll
argument_list|(
name|map
operator|.
name|getProcedureMap
argument_list|()
argument_list|)
expr_stmt|;
comment|// index embeddables
name|embeddables
operator|.
name|putAll
argument_list|(
name|map
operator|.
name|getEmbeddableMap
argument_list|()
argument_list|)
expr_stmt|;
comment|// index query descriptors
name|queryDesriptors
operator|.
name|putAll
argument_list|(
name|map
operator|.
name|getQueryDescriptorMap
argument_list|()
argument_list|)
expr_stmt|;
block|}
comment|// restart the map iterator to index inheritance
for|for
control|(
name|DataMap
name|map
range|:
name|maps
control|)
block|{
comment|// index ObjEntity inheritance
for|for
control|(
name|ObjEntity
name|oe
range|:
name|map
operator|.
name|getObjEntities
argument_list|()
control|)
block|{
comment|// build inheritance tree
name|EntityInheritanceTree
name|node
init|=
name|entityInheritanceCache
operator|.
name|get
argument_list|(
name|oe
operator|.
name|getName
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|node
operator|==
literal|null
condition|)
block|{
name|node
operator|=
operator|new
name|EntityInheritanceTree
argument_list|(
name|oe
argument_list|)
expr_stmt|;
name|entityInheritanceCache
operator|.
name|put
argument_list|(
name|oe
operator|.
name|getName
argument_list|()
argument_list|,
name|node
argument_list|)
expr_stmt|;
block|}
name|String
name|superOEName
init|=
name|oe
operator|.
name|getSuperEntityName
argument_list|()
decl_stmt|;
if|if
condition|(
name|superOEName
operator|!=
literal|null
condition|)
block|{
name|EntityInheritanceTree
name|superNode
init|=
name|entityInheritanceCache
operator|.
name|get
argument_list|(
name|superOEName
argument_list|)
decl_stmt|;
if|if
condition|(
name|superNode
operator|==
literal|null
condition|)
block|{
comment|// do direct entity lookup to avoid recursive cache
comment|// rebuild
name|ObjEntity
name|superOE
init|=
name|objEntities
operator|.
name|get
argument_list|(
name|superOEName
argument_list|)
decl_stmt|;
if|if
condition|(
name|superOE
operator|!=
literal|null
condition|)
block|{
name|superNode
operator|=
operator|new
name|EntityInheritanceTree
argument_list|(
name|superOE
argument_list|)
expr_stmt|;
name|entityInheritanceCache
operator|.
name|put
argument_list|(
name|superOEName
argument_list|,
name|superNode
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// bad mapping? Or most likely some classloader
comment|// issue
name|logger
operator|.
name|warn
argument_list|(
literal|"No super entity mapping for '"
operator|+
name|superOEName
operator|+
literal|"'"
argument_list|)
expr_stmt|;
continue|continue;
block|}
block|}
name|superNode
operator|.
name|addChildNode
argument_list|(
name|node
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
specifier|public
name|Embeddable
name|getEmbeddable
parameter_list|(
name|String
name|className
parameter_list|)
block|{
return|return
name|embeddables
operator|.
name|get
argument_list|(
name|className
argument_list|)
return|;
block|}
specifier|public
name|SQLResult
name|getResult
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|results
operator|.
name|get
argument_list|(
name|name
argument_list|)
return|;
block|}
specifier|public
name|EntityInheritanceTree
name|getInheritanceTree
parameter_list|(
name|String
name|entityName
parameter_list|)
block|{
return|return
name|entityInheritanceCache
operator|.
name|get
argument_list|(
name|entityName
argument_list|)
return|;
block|}
specifier|public
name|Procedure
name|getProcedure
parameter_list|(
name|String
name|procedureName
parameter_list|)
block|{
return|return
name|procedures
operator|.
name|get
argument_list|(
name|procedureName
argument_list|)
return|;
block|}
specifier|public
name|QueryDescriptor
name|getQueryDescriptor
parameter_list|(
name|String
name|queryName
parameter_list|)
block|{
return|return
name|queryDesriptors
operator|.
name|get
argument_list|(
name|queryName
argument_list|)
return|;
block|}
specifier|public
name|DbEntity
name|getDbEntity
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|dbEntities
operator|.
name|get
argument_list|(
name|name
argument_list|)
return|;
block|}
specifier|public
name|ObjEntity
name|getObjEntity
parameter_list|(
name|Class
argument_list|<
name|?
argument_list|>
name|entityClass
parameter_list|)
block|{
name|ObjEntity
name|entity
init|=
name|objEntitiesByClassName
operator|.
name|get
argument_list|(
name|entityClass
operator|.
name|getName
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|entity
operator|==
name|OBJ_DUPLICATE_MARKER
condition|)
block|{
throw|throw
operator|new
name|CayenneRuntimeException
argument_list|(
literal|"Can't perform lookup. There is more than one ObjEntity mapped to %s"
argument_list|,
name|entityClass
operator|.
name|getName
argument_list|()
argument_list|)
throw|;
block|}
return|return
name|entity
return|;
block|}
specifier|public
name|ObjEntity
name|getObjEntity
parameter_list|(
name|Persistent
name|object
parameter_list|)
block|{
name|ObjectId
name|id
init|=
name|object
operator|.
name|getObjectId
argument_list|()
decl_stmt|;
if|if
condition|(
name|id
operator|!=
literal|null
condition|)
block|{
return|return
name|getObjEntity
argument_list|(
name|id
operator|.
name|getEntityName
argument_list|()
argument_list|)
return|;
block|}
else|else
block|{
return|return
name|getObjEntity
argument_list|(
name|object
operator|.
name|getClass
argument_list|()
argument_list|)
return|;
block|}
block|}
specifier|public
name|ObjEntity
name|getObjEntity
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|objEntities
operator|.
name|get
argument_list|(
name|name
argument_list|)
return|;
block|}
specifier|public
name|Collection
argument_list|<
name|DbEntity
argument_list|>
name|getDbEntities
parameter_list|()
block|{
comment|// TODO: LEGACY SUPPORT:
comment|// some downstream code (like Modeler and merge framework) expect
comment|// always fresh list here, so instead of doing the right thing of
comment|// refreshing the cache and returning cache.entries(), we are scanning
comment|// the list of DataMaps.
if|if
condition|(
name|maps
operator|.
name|size
argument_list|()
operator|==
literal|0
condition|)
block|{
return|return
name|Collections
operator|.
name|emptyList
argument_list|()
return|;
block|}
if|if
condition|(
name|maps
operator|.
name|size
argument_list|()
operator|==
literal|1
condition|)
block|{
return|return
name|maps
operator|.
name|iterator
argument_list|()
operator|.
name|next
argument_list|()
operator|.
name|getDbEntities
argument_list|()
return|;
block|}
name|CompositeCollection
name|c
init|=
operator|new
name|CompositeCollection
argument_list|()
decl_stmt|;
for|for
control|(
name|DataMap
name|map
range|:
name|maps
control|)
block|{
name|c
operator|.
name|addComposited
argument_list|(
name|map
operator|.
name|getDbEntities
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|c
return|;
block|}
specifier|public
name|Collection
argument_list|<
name|Procedure
argument_list|>
name|getProcedures
parameter_list|()
block|{
comment|// TODO: LEGACY SUPPORT:
comment|// some downstream code (like Modeler and merge framework) expect
comment|// always fresh list here, so instead of doing the right thing of
comment|// refreshing the cache and returning cache.entries(), we are scanning
comment|// the list of DataMaps.
if|if
condition|(
name|maps
operator|.
name|size
argument_list|()
operator|==
literal|0
condition|)
block|{
return|return
name|Collections
operator|.
name|emptyList
argument_list|()
return|;
block|}
if|if
condition|(
name|maps
operator|.
name|size
argument_list|()
operator|==
literal|1
condition|)
block|{
return|return
name|maps
operator|.
name|iterator
argument_list|()
operator|.
name|next
argument_list|()
operator|.
name|getProcedures
argument_list|()
return|;
block|}
name|CompositeCollection
name|c
init|=
operator|new
name|CompositeCollection
argument_list|()
decl_stmt|;
for|for
control|(
name|DataMap
name|map
range|:
name|maps
control|)
block|{
name|c
operator|.
name|addComposited
argument_list|(
name|map
operator|.
name|getProcedures
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|c
return|;
block|}
specifier|public
name|Collection
argument_list|<
name|QueryDescriptor
argument_list|>
name|getQueryDescriptors
parameter_list|()
block|{
comment|// TODO: LEGACY SUPPORT:
comment|// some downstream code (like Modeler and merge framework) expect
comment|// always fresh list here, so instead of doing the right thing of
comment|// refreshing the cache and returning cache.entries(), we are scanning
comment|// the list of DataMaps.
if|if
condition|(
name|maps
operator|.
name|size
argument_list|()
operator|==
literal|0
condition|)
block|{
return|return
name|Collections
operator|.
name|emptyList
argument_list|()
return|;
block|}
if|if
condition|(
name|maps
operator|.
name|size
argument_list|()
operator|==
literal|1
condition|)
block|{
return|return
name|maps
operator|.
name|iterator
argument_list|()
operator|.
name|next
argument_list|()
operator|.
name|getQueryDescriptors
argument_list|()
return|;
block|}
name|CompositeCollection
name|c
init|=
operator|new
name|CompositeCollection
argument_list|()
decl_stmt|;
for|for
control|(
name|DataMap
name|map
range|:
name|maps
control|)
block|{
name|c
operator|.
name|addComposited
argument_list|(
name|map
operator|.
name|getQueryDescriptors
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|c
return|;
block|}
specifier|public
name|Collection
argument_list|<
name|ObjEntity
argument_list|>
name|getObjEntities
parameter_list|()
block|{
comment|// TODO: LEGACY SUPPORT:
comment|// some downstream code (like Modeler and merge framework) expect
comment|// always fresh list here, so instead of doing the right thing of
comment|// refreshing the cache and returning cache.entries(), we are scanning
comment|// the list of DataMaps.
if|if
condition|(
name|maps
operator|.
name|size
argument_list|()
operator|==
literal|0
condition|)
block|{
return|return
name|Collections
operator|.
name|emptyList
argument_list|()
return|;
block|}
if|if
condition|(
name|maps
operator|.
name|size
argument_list|()
operator|==
literal|1
condition|)
block|{
return|return
name|maps
operator|.
name|iterator
argument_list|()
operator|.
name|next
argument_list|()
operator|.
name|getObjEntities
argument_list|()
return|;
block|}
name|CompositeCollection
name|c
init|=
operator|new
name|CompositeCollection
argument_list|()
decl_stmt|;
for|for
control|(
name|DataMap
name|map
range|:
name|maps
control|)
block|{
name|c
operator|.
name|addComposited
argument_list|(
name|map
operator|.
name|getObjEntities
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|c
return|;
block|}
specifier|public
name|Collection
argument_list|<
name|Embeddable
argument_list|>
name|getEmbeddables
parameter_list|()
block|{
comment|// TODO: LEGACY SUPPORT:
comment|// some downstream code (like Modeler and merge framework) expect
comment|// always fresh list here, so instead of doing the right thing of
comment|// refreshing the cache and returning cache.entries(), we are scanning
comment|// the list of DataMaps.
if|if
condition|(
name|maps
operator|.
name|size
argument_list|()
operator|==
literal|0
condition|)
block|{
return|return
name|Collections
operator|.
name|emptyList
argument_list|()
return|;
block|}
if|if
condition|(
name|maps
operator|.
name|size
argument_list|()
operator|==
literal|1
condition|)
block|{
return|return
name|maps
operator|.
name|iterator
argument_list|()
operator|.
name|next
argument_list|()
operator|.
name|getEmbeddables
argument_list|()
return|;
block|}
name|CompositeCollection
name|c
init|=
operator|new
name|CompositeCollection
argument_list|()
decl_stmt|;
for|for
control|(
name|DataMap
name|map
range|:
name|maps
control|)
block|{
name|c
operator|.
name|addComposited
argument_list|(
name|map
operator|.
name|getEmbeddables
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|c
return|;
block|}
specifier|public
name|Collection
argument_list|<
name|SQLResult
argument_list|>
name|getResults
parameter_list|()
block|{
comment|// TODO: LEGACY SUPPORT:
comment|// some downstream code (like Modeler and merge framework) expect
comment|// always fresh list here, so instead of doing the right thing of
comment|// refreshing the cache and returning cache.entries(), we are scanning
comment|// the list of DataMaps.
if|if
condition|(
name|maps
operator|.
name|size
argument_list|()
operator|==
literal|0
condition|)
block|{
return|return
name|Collections
operator|.
name|emptyList
argument_list|()
return|;
block|}
if|if
condition|(
name|maps
operator|.
name|size
argument_list|()
operator|==
literal|1
condition|)
block|{
return|return
name|maps
operator|.
name|iterator
argument_list|()
operator|.
name|next
argument_list|()
operator|.
name|getResults
argument_list|()
return|;
block|}
name|CompositeCollection
name|c
init|=
operator|new
name|CompositeCollection
argument_list|()
decl_stmt|;
for|for
control|(
name|DataMap
name|map
range|:
name|maps
control|)
block|{
name|c
operator|.
name|addComposited
argument_list|(
name|map
operator|.
name|getResults
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|c
return|;
block|}
block|}
end_class

end_unit

