begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    https://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|ConfigurationNodeVisitor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|query
operator|.
name|ProcedureQuery
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|util
operator|.
name|XMLEncoder
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_comment
comment|/**  * @since 4.0  */
end_comment

begin_class
specifier|public
class|class
name|ProcedureQueryDescriptor
extends|extends
name|QueryDescriptor
block|{
specifier|protected
name|String
name|resultEntityName
decl_stmt|;
specifier|public
name|ProcedureQueryDescriptor
parameter_list|()
block|{
name|super
argument_list|(
name|PROCEDURE_QUERY
argument_list|)
expr_stmt|;
block|}
comment|/**      * Returns result entity name.      */
specifier|public
name|String
name|getResultEntityName
parameter_list|()
block|{
return|return
name|resultEntityName
return|;
block|}
comment|/**      * Sets result entity name.      */
specifier|public
name|void
name|setResultEntityName
parameter_list|(
name|String
name|resultEntityName
parameter_list|)
block|{
name|this
operator|.
name|resultEntityName
operator|=
name|resultEntityName
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|ProcedureQuery
name|buildQuery
parameter_list|()
block|{
name|ProcedureQuery
name|procedureQuery
init|=
operator|new
name|ProcedureQuery
argument_list|()
decl_stmt|;
if|if
condition|(
name|root
operator|!=
literal|null
condition|)
block|{
name|procedureQuery
operator|.
name|setRoot
argument_list|(
name|root
argument_list|)
expr_stmt|;
block|}
name|procedureQuery
operator|.
name|setResultEntityName
argument_list|(
name|this
operator|.
name|getResultEntityName
argument_list|()
argument_list|)
expr_stmt|;
name|procedureQuery
operator|.
name|initWithProperties
argument_list|(
name|this
operator|.
name|getProperties
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|procedureQuery
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|encodeAsXML
parameter_list|(
name|XMLEncoder
name|encoder
parameter_list|,
name|ConfigurationNodeVisitor
name|delegate
parameter_list|)
block|{
name|encoder
operator|.
name|start
argument_list|(
literal|"query"
argument_list|)
operator|.
name|attribute
argument_list|(
literal|"name"
argument_list|,
name|getName
argument_list|()
argument_list|)
operator|.
name|attribute
argument_list|(
literal|"type"
argument_list|,
name|getType
argument_list|()
argument_list|)
operator|.
name|attribute
argument_list|(
literal|"root"
argument_list|,
name|QueryDescriptor
operator|.
name|PROCEDURE_ROOT
argument_list|)
expr_stmt|;
name|String
name|rootString
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|root
operator|instanceof
name|String
condition|)
block|{
name|rootString
operator|=
name|root
operator|.
name|toString
argument_list|()
expr_stmt|;
block|}
if|else if
condition|(
name|root
operator|instanceof
name|Procedure
condition|)
block|{
name|rootString
operator|=
operator|(
operator|(
name|Procedure
operator|)
name|root
operator|)
operator|.
name|getName
argument_list|()
expr_stmt|;
block|}
name|encoder
operator|.
name|attribute
argument_list|(
literal|"root-name"
argument_list|,
name|rootString
argument_list|)
operator|.
name|attribute
argument_list|(
literal|"result-entity"
argument_list|,
name|resultEntityName
argument_list|)
expr_stmt|;
comment|// print properties
name|encodeProperties
argument_list|(
name|encoder
argument_list|)
expr_stmt|;
name|delegate
operator|.
name|visitQuery
argument_list|(
name|this
argument_list|)
expr_stmt|;
name|encoder
operator|.
name|end
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

