# Since 4GB not enough for build, we use 'sudo' environment with 7.5GB RAM
# Downside: It's starts a little bit slower
# How to fix: Change build setting or fix code.
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
language: java

env:
  - DB_PROFILE=hsql
  - DB_PROFILE=h2
  - DB_PROFILE=derby

jdk:
  - oraclejdk8
  - oraclejdk7

script:
  - mvn verify -q -DcayenneTestConnection=$DB_PROFILE -DcayenneLogLevel=ERROR

# prevent Travis from unneeded "mvn install" run
install: /bin/true

cache:
  directories:
    - $HOME/.m2
