begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    https://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|remote
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|testdo
operator|.
name|mt
operator|.
name|MtTable1
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|testdo
operator|.
name|mt
operator|.
name|MtTable2
import|;
end_import

begin_class
specifier|public
class|class
name|ClientChannelServerDiffsListener1
block|{
specifier|public
name|void
name|prePersist
parameter_list|(
name|MtTable1
name|object
parameter_list|)
block|{
name|object
operator|.
name|setGlobalAttribute1
argument_list|(
literal|"XXX"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|preUpdate
parameter_list|(
name|MtTable1
name|object
parameter_list|)
block|{
name|object
operator|.
name|setGlobalAttribute1
argument_list|(
literal|"111"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|prePersistAddRelationship
parameter_list|(
name|MtTable1
name|object
parameter_list|)
block|{
name|object
operator|.
name|addToTable2Array
argument_list|(
name|object
operator|.
name|getObjectContext
argument_list|()
operator|.
name|newObject
argument_list|(
name|MtTable2
operator|.
name|class
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

