begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|jpa
operator|.
name|itest
operator|.
name|ch2
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|persistence
operator|.
name|Query
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|itest
operator|.
name|ItestTableUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|itest
operator|.
name|jpa
operator|.
name|EntityManagerCase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|jpa
operator|.
name|itest
operator|.
name|ch2
operator|.
name|entity
operator|.
name|SingleTableInheritanceSub1
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|jpa
operator|.
name|itest
operator|.
name|ch2
operator|.
name|entity
operator|.
name|SingleTableInheritanceSub2
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|jpa
operator|.
name|itest
operator|.
name|ch2
operator|.
name|entity
operator|.
name|SingleTableInheritanceSuper1
import|;
end_import

begin_class
specifier|public
class|class
name|_2_1_10_1_SingleTablePerClassTest
extends|extends
name|EntityManagerCase
block|{
specifier|public
name|void
name|testSelectSuper
parameter_list|()
throws|throws
name|Exception
block|{
name|ItestTableUtils
name|helper
init|=
name|getTableHelper
argument_list|(
literal|"ST_INHERITANCE"
argument_list|)
decl_stmt|;
name|helper
operator|.
name|deleteAll
argument_list|()
expr_stmt|;
name|helper
operator|.
name|setColumns
argument_list|(
literal|"id"
argument_list|,
literal|"objectType"
argument_list|,
literal|"propertyA"
argument_list|,
literal|"propertyB"
argument_list|,
literal|"propertyC"
argument_list|)
expr_stmt|;
name|helper
operator|.
name|insert
argument_list|(
literal|1
argument_list|,
literal|"A"
argument_list|,
literal|"1"
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|helper
operator|.
name|insert
argument_list|(
literal|2
argument_list|,
literal|"A"
argument_list|,
literal|"2"
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|helper
operator|.
name|insert
argument_list|(
literal|3
argument_list|,
literal|"B"
argument_list|,
literal|"3"
argument_list|,
literal|"BX"
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|helper
operator|.
name|insert
argument_list|(
literal|4
argument_list|,
literal|"C"
argument_list|,
literal|"4"
argument_list|,
literal|null
argument_list|,
literal|"CX"
argument_list|)
expr_stmt|;
name|Query
name|query
init|=
name|getEntityManager
argument_list|()
operator|.
name|createQuery
argument_list|(
literal|"select a FROM SingleTableInheritanceSuper1 a ORDER BY a.propertyA"
argument_list|)
decl_stmt|;
name|List
argument_list|<
name|?
argument_list|>
name|results
init|=
name|query
operator|.
name|getResultList
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|4
argument_list|,
name|results
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|SingleTableInheritanceSuper1
operator|.
name|class
operator|.
name|getName
argument_list|()
argument_list|,
name|results
operator|.
name|get
argument_list|(
literal|0
argument_list|)
operator|.
name|getClass
argument_list|()
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|SingleTableInheritanceSuper1
operator|.
name|class
operator|.
name|getName
argument_list|()
argument_list|,
name|results
operator|.
name|get
argument_list|(
literal|1
argument_list|)
operator|.
name|getClass
argument_list|()
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|SingleTableInheritanceSub1
operator|.
name|class
operator|.
name|getName
argument_list|()
argument_list|,
name|results
operator|.
name|get
argument_list|(
literal|2
argument_list|)
operator|.
name|getClass
argument_list|()
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|SingleTableInheritanceSub2
operator|.
name|class
operator|.
name|getName
argument_list|()
argument_list|,
name|results
operator|.
name|get
argument_list|(
literal|3
argument_list|)
operator|.
name|getClass
argument_list|()
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testSelectSub
parameter_list|()
throws|throws
name|Exception
block|{
name|ItestTableUtils
name|helper
init|=
name|getTableHelper
argument_list|(
literal|"ST_INHERITANCE"
argument_list|)
decl_stmt|;
name|helper
operator|.
name|deleteAll
argument_list|()
expr_stmt|;
name|helper
operator|.
name|setColumns
argument_list|(
literal|"id"
argument_list|,
literal|"objectType"
argument_list|,
literal|"propertyA"
argument_list|,
literal|"propertyB"
argument_list|,
literal|"propertyC"
argument_list|)
expr_stmt|;
name|helper
operator|.
name|insert
argument_list|(
literal|1
argument_list|,
literal|"A"
argument_list|,
literal|"1"
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|helper
operator|.
name|insert
argument_list|(
literal|2
argument_list|,
literal|"A"
argument_list|,
literal|"2"
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|helper
operator|.
name|insert
argument_list|(
literal|3
argument_list|,
literal|"B"
argument_list|,
literal|"3"
argument_list|,
literal|"BX"
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|helper
operator|.
name|insert
argument_list|(
literal|4
argument_list|,
literal|"C"
argument_list|,
literal|"4"
argument_list|,
literal|null
argument_list|,
literal|"CX"
argument_list|)
expr_stmt|;
name|Query
name|query
init|=
name|getEntityManager
argument_list|()
operator|.
name|createQuery
argument_list|(
literal|"select a FROM SingleTableInheritanceSub1 a ORDER BY a.propertyA"
argument_list|)
decl_stmt|;
name|List
argument_list|<
name|?
argument_list|>
name|results
init|=
name|query
operator|.
name|getResultList
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|results
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|SingleTableInheritanceSub1
operator|.
name|class
operator|.
name|getName
argument_list|()
argument_list|,
name|results
operator|.
name|get
argument_list|(
literal|0
argument_list|)
operator|.
name|getClass
argument_list|()
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

