begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|dialog
operator|.
name|pref
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JPanel
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JScrollPane
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JTree
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|tree
operator|.
name|DefaultMutableTreeNode
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|tree
operator|.
name|TreeCellRenderer
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Dimension
import|;
end_import

begin_comment
comment|/**  * @since 4.0  */
end_comment

begin_class
specifier|public
class|class
name|TreeView
extends|extends
name|JPanel
block|{
specifier|protected
name|JTree
name|tree
decl_stmt|;
specifier|protected
name|JScrollPane
name|scrollPane
decl_stmt|;
specifier|public
name|JTree
name|getTree
parameter_list|()
block|{
return|return
name|tree
return|;
block|}
specifier|public
name|void
name|setTree
parameter_list|(
name|JTree
name|tree
parameter_list|)
block|{
name|this
operator|.
name|tree
operator|=
name|tree
expr_stmt|;
block|}
specifier|public
name|TreeView
parameter_list|(
name|DefaultMutableTreeNode
name|root
parameter_list|)
block|{
name|this
operator|.
name|tree
operator|=
operator|new
name|JTree
argument_list|(
name|root
argument_list|)
expr_stmt|;
name|TreeCellRenderer
name|renderer
init|=
operator|new
name|FilteredTreeCellRenderer
argument_list|()
decl_stmt|;
name|tree
operator|.
name|setCellRenderer
argument_list|(
name|renderer
argument_list|)
expr_stmt|;
name|scrollPane
operator|=
operator|new
name|JScrollPane
argument_list|(
name|tree
argument_list|)
expr_stmt|;
name|scrollPane
operator|.
name|setPreferredSize
argument_list|(
operator|new
name|Dimension
argument_list|(
literal|210
argument_list|,
literal|300
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|JScrollPane
name|getScrollPane
parameter_list|()
block|{
return|return
name|scrollPane
return|;
block|}
block|}
end_class

end_unit

