begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    https://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|dbsync
operator|.
name|merge
operator|.
name|builders
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|DataMap
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|DbEntity
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|EntityResolver
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|ObjEntity
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_comment
comment|/**  * @since 4.0.  */
end_comment

begin_class
specifier|public
class|class
name|DataMapBuilder
extends|extends
name|DefaultBuilder
argument_list|<
name|DataMap
argument_list|>
block|{
specifier|public
name|DataMapBuilder
parameter_list|()
block|{
name|this
argument_list|(
operator|new
name|DataMap
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|DataMapBuilder
parameter_list|(
name|DataMap
name|dataMap
parameter_list|)
block|{
name|super
argument_list|(
name|dataMap
argument_list|)
expr_stmt|;
block|}
specifier|public
name|DataMapBuilder
name|with
parameter_list|(
name|DbEntity
modifier|...
name|entities
parameter_list|)
block|{
for|for
control|(
name|DbEntity
name|entity
range|:
name|entities
control|)
block|{
name|obj
operator|.
name|addDbEntity
argument_list|(
name|entity
argument_list|)
expr_stmt|;
block|}
return|return
name|this
return|;
block|}
specifier|public
name|DataMapBuilder
name|with
parameter_list|(
name|DbEntityBuilder
modifier|...
name|entities
parameter_list|)
block|{
for|for
control|(
name|DbEntityBuilder
name|entity
range|:
name|entities
control|)
block|{
name|obj
operator|.
name|addDbEntity
argument_list|(
name|entity
operator|.
name|build
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|this
return|;
block|}
specifier|public
name|DataMapBuilder
name|withDbEntities
parameter_list|(
name|int
name|count
parameter_list|)
block|{
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|count
condition|;
name|i
operator|++
control|)
block|{
name|obj
operator|.
name|addDbEntity
argument_list|(
name|ObjectMother
operator|.
name|dbEntity
argument_list|()
operator|.
name|random
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|this
return|;
block|}
specifier|public
name|DataMapBuilder
name|with
parameter_list|(
name|ObjEntity
modifier|...
name|entities
parameter_list|)
block|{
for|for
control|(
name|ObjEntity
name|entity
range|:
name|entities
control|)
block|{
name|obj
operator|.
name|addObjEntity
argument_list|(
name|entity
argument_list|)
expr_stmt|;
block|}
return|return
name|this
return|;
block|}
specifier|public
name|DataMapBuilder
name|with
parameter_list|(
name|ObjEntityBuilder
modifier|...
name|entities
parameter_list|)
block|{
for|for
control|(
name|ObjEntityBuilder
name|entity
range|:
name|entities
control|)
block|{
name|obj
operator|.
name|addObjEntity
argument_list|(
name|entity
operator|.
name|build
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|this
return|;
block|}
specifier|public
name|DataMapBuilder
name|withObjEntities
parameter_list|(
name|int
name|count
parameter_list|)
block|{
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|count
condition|;
name|i
operator|++
control|)
block|{
name|obj
operator|.
name|addObjEntity
argument_list|(
name|ObjectMother
operator|.
name|objEntity
argument_list|()
operator|.
name|random
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|this
return|;
block|}
specifier|public
name|DataMapBuilder
name|join
parameter_list|(
name|String
name|from
parameter_list|,
name|String
name|to
parameter_list|)
block|{
return|return
name|join
argument_list|(
literal|null
argument_list|,
name|from
argument_list|,
name|to
argument_list|)
return|;
block|}
specifier|public
name|DataMapBuilder
name|join
parameter_list|(
name|String
name|name
parameter_list|,
name|String
name|from
parameter_list|,
name|String
name|to
parameter_list|)
block|{
name|String
index|[]
name|fromSplit
init|=
name|from
operator|.
name|split
argument_list|(
literal|"\\."
argument_list|)
decl_stmt|;
name|DbEntity
name|fromEntity
init|=
name|obj
operator|.
name|getDbEntity
argument_list|(
name|fromSplit
index|[
literal|0
index|]
argument_list|)
decl_stmt|;
if|if
condition|(
name|fromEntity
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"Entity '"
operator|+
name|fromSplit
index|[
literal|0
index|]
operator|+
literal|"' is undefined"
argument_list|)
throw|;
block|}
name|String
index|[]
name|toSplit
init|=
name|to
operator|.
name|split
argument_list|(
literal|"\\."
argument_list|)
decl_stmt|;
name|fromEntity
operator|.
name|addRelationship
argument_list|(
operator|new
name|DbRelationshipBuilder
argument_list|(
name|name
argument_list|)
operator|.
name|from
argument_list|(
name|fromEntity
argument_list|,
name|fromSplit
index|[
literal|1
index|]
argument_list|)
operator|.
name|to
argument_list|(
name|toSplit
index|[
literal|0
index|]
argument_list|,
name|toSplit
index|[
literal|1
index|]
argument_list|)
operator|.
name|build
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
specifier|public
name|DataMap
name|build
parameter_list|()
block|{
if|if
condition|(
name|obj
operator|.
name|getNamespace
argument_list|()
operator|==
literal|null
condition|)
block|{
name|obj
operator|.
name|setNamespace
argument_list|(
operator|new
name|EntityResolver
argument_list|(
name|Collections
operator|.
name|singleton
argument_list|(
name|obj
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
return|return
name|obj
return|;
block|}
annotation|@
name|Override
specifier|public
name|DataMap
name|random
parameter_list|()
block|{
if|if
condition|(
name|dataFactory
operator|.
name|chance
argument_list|(
literal|90
argument_list|)
condition|)
block|{
name|withDbEntities
argument_list|(
name|dataFactory
operator|.
name|getNumberUpTo
argument_list|(
literal|10
argument_list|)
argument_list|)
expr_stmt|;
block|}
return|return
name|build
argument_list|()
return|;
block|}
block|}
end_class

end_unit

