begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|java8
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|ObjectContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|java8
operator|.
name|db
operator|.
name|LocalDateTestEntity
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|java8
operator|.
name|db
operator|.
name|LocalDateTimeTestEntity
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|java8
operator|.
name|db
operator|.
name|LocalTimeTestEntity
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|query
operator|.
name|ObjectSelect
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|test
operator|.
name|jdbc
operator|.
name|DBHelper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Before
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|java
operator|.
name|sql
operator|.
name|SQLException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|time
operator|.
name|LocalDate
import|;
end_import

begin_import
import|import
name|java
operator|.
name|time
operator|.
name|LocalDateTime
import|;
end_import

begin_import
import|import
name|java
operator|.
name|time
operator|.
name|LocalTime
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertEquals
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertNotNull
import|;
end_import

begin_class
specifier|public
class|class
name|Java8TimeIT
extends|extends
name|RuntimeBase
block|{
annotation|@
name|Before
specifier|public
name|void
name|before
parameter_list|()
throws|throws
name|SQLException
block|{
name|DBHelper
name|dbHelper
init|=
operator|new
name|DBHelper
argument_list|(
name|runtime
operator|.
name|getDataSource
argument_list|()
argument_list|)
decl_stmt|;
name|dbHelper
operator|.
name|deleteAll
argument_list|(
literal|"LOCAL_DATE_TEST"
argument_list|)
expr_stmt|;
name|dbHelper
operator|.
name|deleteAll
argument_list|(
literal|"LOCAL_DATETIME_TEST"
argument_list|)
expr_stmt|;
name|dbHelper
operator|.
name|deleteAll
argument_list|(
literal|"LOCAL_TIME_TEST"
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testJava8LocalDate_Null
parameter_list|()
block|{
name|ObjectContext
name|context
init|=
name|runtime
operator|.
name|newContext
argument_list|()
decl_stmt|;
name|LocalDateTestEntity
name|localDateTestEntity
init|=
name|context
operator|.
name|newObject
argument_list|(
name|LocalDateTestEntity
operator|.
name|class
argument_list|)
decl_stmt|;
name|localDateTestEntity
operator|.
name|setDate
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|context
operator|.
name|commitChanges
argument_list|()
expr_stmt|;
name|LocalDateTestEntity
name|testRead
init|=
name|ObjectSelect
operator|.
name|query
argument_list|(
name|LocalDateTestEntity
operator|.
name|class
argument_list|)
operator|.
name|selectOne
argument_list|(
name|context
argument_list|)
decl_stmt|;
name|Assert
operator|.
name|assertNull
argument_list|(
name|testRead
operator|.
name|getDate
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testJava8LocalDate
parameter_list|()
block|{
name|ObjectContext
name|context
init|=
name|runtime
operator|.
name|newContext
argument_list|()
decl_stmt|;
name|LocalDateTestEntity
name|localDateTestEntity
init|=
name|context
operator|.
name|newObject
argument_list|(
name|LocalDateTestEntity
operator|.
name|class
argument_list|)
decl_stmt|;
name|LocalDate
name|localDate
init|=
name|LocalDate
operator|.
name|now
argument_list|()
decl_stmt|;
name|localDateTestEntity
operator|.
name|setDate
argument_list|(
name|localDate
argument_list|)
expr_stmt|;
name|context
operator|.
name|commitChanges
argument_list|()
expr_stmt|;
name|LocalDateTestEntity
name|testRead
init|=
name|ObjectSelect
operator|.
name|query
argument_list|(
name|LocalDateTestEntity
operator|.
name|class
argument_list|)
operator|.
name|selectOne
argument_list|(
name|context
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|testRead
operator|.
name|getDate
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|LocalDate
operator|.
name|class
argument_list|,
name|testRead
operator|.
name|getDate
argument_list|()
operator|.
name|getClass
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|localDate
argument_list|,
name|testRead
operator|.
name|getDate
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testJava8LocalTime
parameter_list|()
block|{
name|ObjectContext
name|context
init|=
name|runtime
operator|.
name|newContext
argument_list|()
decl_stmt|;
name|LocalTimeTestEntity
name|localTimeTestEntity
init|=
name|context
operator|.
name|newObject
argument_list|(
name|LocalTimeTestEntity
operator|.
name|class
argument_list|)
decl_stmt|;
name|LocalTime
name|localTime
init|=
name|LocalTime
operator|.
name|now
argument_list|()
decl_stmt|;
name|localTimeTestEntity
operator|.
name|setTime
argument_list|(
name|localTime
argument_list|)
expr_stmt|;
name|context
operator|.
name|commitChanges
argument_list|()
expr_stmt|;
name|LocalTimeTestEntity
name|testRead
init|=
name|ObjectSelect
operator|.
name|query
argument_list|(
name|LocalTimeTestEntity
operator|.
name|class
argument_list|)
operator|.
name|selectOne
argument_list|(
name|context
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|testRead
operator|.
name|getTime
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|LocalTime
operator|.
name|class
argument_list|,
name|testRead
operator|.
name|getTime
argument_list|()
operator|.
name|getClass
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|localTime
operator|.
name|toSecondOfDay
argument_list|()
argument_list|,
name|testRead
operator|.
name|getTime
argument_list|()
operator|.
name|toSecondOfDay
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testJava8LocalDateTime
parameter_list|()
block|{
name|ObjectContext
name|context
init|=
name|runtime
operator|.
name|newContext
argument_list|()
decl_stmt|;
name|LocalDateTimeTestEntity
name|localDateTimeTestEntity
init|=
name|context
operator|.
name|newObject
argument_list|(
name|LocalDateTimeTestEntity
operator|.
name|class
argument_list|)
decl_stmt|;
name|LocalDateTime
name|localDateTime
init|=
name|LocalDateTime
operator|.
name|now
argument_list|()
decl_stmt|;
name|localDateTimeTestEntity
operator|.
name|setTimestamp
argument_list|(
name|localDateTime
argument_list|)
expr_stmt|;
name|context
operator|.
name|commitChanges
argument_list|()
expr_stmt|;
name|LocalDateTimeTestEntity
name|testRead
init|=
name|ObjectSelect
operator|.
name|query
argument_list|(
name|LocalDateTimeTestEntity
operator|.
name|class
argument_list|)
operator|.
name|selectOne
argument_list|(
name|context
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|testRead
operator|.
name|getTimestamp
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|LocalDateTime
operator|.
name|class
argument_list|,
name|testRead
operator|.
name|getTimestamp
argument_list|()
operator|.
name|getClass
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|localDateTime
argument_list|,
name|testRead
operator|.
name|getTimestamp
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|columnSelectWithJava8Type
parameter_list|()
block|{
name|ObjectContext
name|context
init|=
name|runtime
operator|.
name|newContext
argument_list|()
decl_stmt|;
name|LocalDateTime
name|localDateTime
init|=
name|LocalDateTime
operator|.
name|now
argument_list|()
decl_stmt|;
name|LocalDateTimeTestEntity
name|localDateTimeTestEntity
init|=
name|context
operator|.
name|newObject
argument_list|(
name|LocalDateTimeTestEntity
operator|.
name|class
argument_list|)
decl_stmt|;
name|localDateTimeTestEntity
operator|.
name|setTimestamp
argument_list|(
name|localDateTime
argument_list|)
expr_stmt|;
name|context
operator|.
name|commitChanges
argument_list|()
expr_stmt|;
name|LocalDateTime
name|value
init|=
name|ObjectSelect
operator|.
name|query
argument_list|(
name|LocalDateTimeTestEntity
operator|.
name|class
argument_list|)
operator|.
name|column
argument_list|(
name|LocalDateTimeTestEntity
operator|.
name|TIMESTAMP
argument_list|)
operator|.
name|selectOne
argument_list|(
name|context
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|localDateTime
argument_list|,
name|value
argument_list|)
expr_stmt|;
name|LocalDateTime
name|value2
init|=
name|ObjectSelect
operator|.
name|query
argument_list|(
name|LocalDateTimeTestEntity
operator|.
name|class
argument_list|)
operator|.
name|min
argument_list|(
name|LocalDateTimeTestEntity
operator|.
name|TIMESTAMP
argument_list|)
operator|.
name|selectOne
argument_list|(
name|context
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|localDateTime
argument_list|,
name|value2
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

