begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|dialog
operator|.
name|validator
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JFrame
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|DataChannelDescriptor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|DataMap
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|Embeddable
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|ProjectController
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|event
operator|.
name|EmbeddableDisplayEvent
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|project
operator|.
name|validator
operator|.
name|ValidationInfo
import|;
end_import

begin_class
specifier|public
class|class
name|EmbeddableErrorMsg
extends|extends
name|ValidationDisplayHandler
block|{
specifier|protected
name|DataMap
name|map
decl_stmt|;
specifier|protected
name|Embeddable
name|embeddable
decl_stmt|;
specifier|public
name|EmbeddableErrorMsg
parameter_list|(
name|ValidationInfo
name|result
parameter_list|)
block|{
name|super
argument_list|(
name|result
argument_list|)
expr_stmt|;
name|Object
index|[]
name|path
init|=
name|result
operator|.
name|getPath
argument_list|()
operator|.
name|getPath
argument_list|()
decl_stmt|;
name|int
name|len
init|=
name|path
operator|.
name|length
decl_stmt|;
if|if
condition|(
name|len
operator|>=
literal|1
condition|)
block|{
name|embeddable
operator|=
operator|(
name|Embeddable
operator|)
name|path
index|[
name|len
operator|-
literal|1
index|]
expr_stmt|;
block|}
if|if
condition|(
name|len
operator|>=
literal|2
condition|)
block|{
name|map
operator|=
operator|(
name|DataMap
operator|)
name|path
index|[
name|len
operator|-
literal|2
index|]
expr_stmt|;
block|}
if|if
condition|(
name|len
operator|>=
literal|3
condition|)
block|{
name|domain
operator|=
operator|(
name|DataChannelDescriptor
operator|)
name|path
index|[
name|len
operator|-
literal|3
index|]
expr_stmt|;
block|}
block|}
annotation|@
name|Override
specifier|public
name|void
name|displayField
parameter_list|(
name|ProjectController
name|mediator
parameter_list|,
name|JFrame
name|frame
parameter_list|)
block|{
name|EmbeddableDisplayEvent
name|event
init|=
operator|new
name|EmbeddableDisplayEvent
argument_list|(
name|frame
argument_list|,
name|embeddable
argument_list|,
name|map
argument_list|,
name|domain
argument_list|)
decl_stmt|;
name|mediator
operator|.
name|fireEmbeddableDisplayEvent
argument_list|(
name|event
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

