begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|di
operator|.
name|spi
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|di
operator|.
name|DIRuntimeException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|di
operator|.
name|Key
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|di
operator|.
name|ListBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|di
operator|.
name|Provider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|di
operator|.
name|Scope
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|di
operator|.
name|UnorderedListBuilder
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|LinkedHashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|concurrent
operator|.
name|atomic
operator|.
name|AtomicLong
import|;
end_import

begin_comment
comment|/**  * @since 3.1  */
end_comment

begin_class
class|class
name|DefaultListBuilder
parameter_list|<
name|T
parameter_list|>
implements|implements
name|ListBuilder
argument_list|<
name|T
argument_list|>
block|{
specifier|protected
specifier|static
name|AtomicLong
name|incrementer
init|=
operator|new
name|AtomicLong
argument_list|()
decl_stmt|;
specifier|protected
name|DefaultInjector
name|injector
decl_stmt|;
specifier|protected
name|Key
argument_list|<
name|List
argument_list|<
name|T
argument_list|>
argument_list|>
name|bindingKey
decl_stmt|;
name|DefaultListBuilder
parameter_list|(
name|Key
argument_list|<
name|List
argument_list|<
name|T
argument_list|>
argument_list|>
name|bindingKey
parameter_list|,
name|DefaultInjector
name|injector
parameter_list|)
block|{
name|this
operator|.
name|injector
operator|=
name|injector
expr_stmt|;
name|this
operator|.
name|bindingKey
operator|=
name|bindingKey
expr_stmt|;
comment|// trigger initialization of the ListProvider right away, as we need to bind an
comment|// empty list even if the user never calls 'put'
name|getListProvider
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|ListBuilder
argument_list|<
name|T
argument_list|>
name|add
parameter_list|(
name|Class
argument_list|<
name|?
extends|extends
name|T
argument_list|>
name|interfaceType
parameter_list|)
throws|throws
name|DIRuntimeException
block|{
name|Key
argument_list|<
name|?
extends|extends
name|T
argument_list|>
name|key
init|=
name|Key
operator|.
name|get
argument_list|(
name|interfaceType
argument_list|)
decl_stmt|;
name|Binding
argument_list|<
name|?
extends|extends
name|T
argument_list|>
name|binding
init|=
name|injector
operator|.
name|getBinding
argument_list|(
name|key
argument_list|)
decl_stmt|;
if|if
condition|(
name|binding
operator|==
literal|null
condition|)
block|{
return|return
name|addWithBinding
argument_list|(
name|interfaceType
argument_list|)
return|;
block|}
name|getListProvider
argument_list|()
operator|.
name|add
argument_list|(
name|key
argument_list|,
name|binding
operator|.
name|getScoped
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
parameter_list|<
name|K
extends|extends
name|T
parameter_list|>
name|ListBuilder
argument_list|<
name|T
argument_list|>
name|addWithBinding
parameter_list|(
name|Class
argument_list|<
name|K
argument_list|>
name|interfaceType
parameter_list|)
block|{
name|Key
argument_list|<
name|K
argument_list|>
name|key
init|=
name|Key
operator|.
name|get
argument_list|(
name|interfaceType
argument_list|)
decl_stmt|;
name|Provider
argument_list|<
name|K
argument_list|>
name|provider0
init|=
operator|new
name|ConstructorInjectingProvider
argument_list|<>
argument_list|(
name|interfaceType
argument_list|,
name|injector
argument_list|)
decl_stmt|;
name|Provider
argument_list|<
name|K
argument_list|>
name|provider1
init|=
operator|new
name|FieldInjectingProvider
argument_list|<>
argument_list|(
name|provider0
argument_list|,
name|injector
argument_list|)
decl_stmt|;
name|injector
operator|.
name|putBinding
argument_list|(
name|key
argument_list|,
name|provider1
argument_list|)
expr_stmt|;
name|getListProvider
argument_list|()
operator|.
name|add
argument_list|(
name|key
argument_list|,
name|injector
operator|.
name|getProvider
argument_list|(
name|key
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|SuppressWarnings
argument_list|(
literal|"unchecked"
argument_list|)
annotation|@
name|Override
specifier|public
name|ListBuilder
argument_list|<
name|T
argument_list|>
name|add
parameter_list|(
name|T
name|object
parameter_list|)
throws|throws
name|DIRuntimeException
block|{
name|Provider
argument_list|<
name|T
argument_list|>
name|provider0
init|=
operator|new
name|InstanceProvider
argument_list|<>
argument_list|(
name|object
argument_list|)
decl_stmt|;
name|Provider
argument_list|<
name|T
argument_list|>
name|provider1
init|=
operator|new
name|FieldInjectingProvider
argument_list|<>
argument_list|(
name|provider0
argument_list|,
name|injector
argument_list|)
decl_stmt|;
name|getListProvider
argument_list|()
operator|.
name|add
argument_list|(
name|Key
operator|.
name|get
argument_list|(
operator|(
name|Class
argument_list|<
name|?
extends|extends
name|T
argument_list|>
operator|)
name|object
operator|.
name|getClass
argument_list|()
argument_list|,
name|String
operator|.
name|valueOf
argument_list|(
name|incrementer
operator|.
name|getAndIncrement
argument_list|()
argument_list|)
argument_list|)
argument_list|,
name|provider1
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
name|ListBuilder
argument_list|<
name|T
argument_list|>
name|add
parameter_list|(
name|Key
argument_list|<
name|T
argument_list|>
name|key
parameter_list|,
name|T
name|object
parameter_list|)
throws|throws
name|DIRuntimeException
block|{
name|Provider
argument_list|<
name|T
argument_list|>
name|provider0
init|=
operator|new
name|InstanceProvider
argument_list|<>
argument_list|(
name|object
argument_list|)
decl_stmt|;
name|Provider
argument_list|<
name|T
argument_list|>
name|provider1
init|=
operator|new
name|FieldInjectingProvider
argument_list|<>
argument_list|(
name|provider0
argument_list|,
name|injector
argument_list|)
decl_stmt|;
name|getListProvider
argument_list|()
operator|.
name|add
argument_list|(
name|key
argument_list|,
name|provider1
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
name|UnorderedListBuilder
argument_list|<
name|T
argument_list|>
name|after
parameter_list|(
name|Class
argument_list|<
name|?
extends|extends
name|T
argument_list|>
name|type
parameter_list|)
block|{
return|return
name|after
argument_list|(
name|Key
operator|.
name|get
argument_list|(
name|type
argument_list|)
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|UnorderedListBuilder
argument_list|<
name|T
argument_list|>
name|after
parameter_list|(
name|Key
argument_list|<
name|?
extends|extends
name|T
argument_list|>
name|key
parameter_list|)
block|{
name|getListProvider
argument_list|()
operator|.
name|after
argument_list|(
name|key
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
name|UnorderedListBuilder
argument_list|<
name|T
argument_list|>
name|before
parameter_list|(
name|Class
argument_list|<
name|?
extends|extends
name|T
argument_list|>
name|type
parameter_list|)
block|{
return|return
name|before
argument_list|(
name|Key
operator|.
name|get
argument_list|(
name|type
argument_list|)
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|UnorderedListBuilder
argument_list|<
name|T
argument_list|>
name|before
parameter_list|(
name|Key
argument_list|<
name|?
extends|extends
name|T
argument_list|>
name|key
parameter_list|)
block|{
name|getListProvider
argument_list|()
operator|.
name|before
argument_list|(
name|key
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
annotation|@
name|Override
specifier|public
name|ListBuilder
argument_list|<
name|T
argument_list|>
name|addAll
parameter_list|(
name|Collection
argument_list|<
name|T
argument_list|>
name|objects
parameter_list|)
throws|throws
name|DIRuntimeException
block|{
name|Map
argument_list|<
name|Key
argument_list|<
name|?
extends|extends
name|T
argument_list|>
argument_list|,
name|Provider
argument_list|<
name|?
extends|extends
name|T
argument_list|>
argument_list|>
name|keyProviderMap
init|=
operator|new
name|LinkedHashMap
argument_list|<>
argument_list|()
decl_stmt|;
for|for
control|(
name|T
name|object
range|:
name|objects
control|)
block|{
name|Provider
argument_list|<
name|T
argument_list|>
name|provider0
init|=
operator|new
name|InstanceProvider
argument_list|<>
argument_list|(
name|object
argument_list|)
decl_stmt|;
name|Provider
argument_list|<
name|T
argument_list|>
name|provider1
init|=
operator|new
name|FieldInjectingProvider
argument_list|<>
argument_list|(
name|provider0
argument_list|,
name|injector
argument_list|)
decl_stmt|;
annotation|@
name|SuppressWarnings
argument_list|(
literal|"unchecked"
argument_list|)
name|Class
argument_list|<
name|?
extends|extends
name|T
argument_list|>
name|objectType
init|=
operator|(
name|Class
argument_list|<
name|?
extends|extends
name|T
argument_list|>
operator|)
name|object
operator|.
name|getClass
argument_list|()
decl_stmt|;
name|keyProviderMap
operator|.
name|put
argument_list|(
name|Key
operator|.
name|get
argument_list|(
name|objectType
argument_list|,
name|String
operator|.
name|valueOf
argument_list|(
name|incrementer
operator|.
name|getAndIncrement
argument_list|()
argument_list|)
argument_list|)
argument_list|,
name|provider1
argument_list|)
expr_stmt|;
block|}
name|getListProvider
argument_list|()
operator|.
name|addAll
argument_list|(
name|keyProviderMap
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
specifier|private
name|ListProvider
argument_list|<
name|T
argument_list|>
name|getListProvider
parameter_list|()
block|{
name|ListProvider
argument_list|<
name|T
argument_list|>
name|provider
decl_stmt|;
name|Binding
argument_list|<
name|List
argument_list|<
name|T
argument_list|>
argument_list|>
name|binding
init|=
name|injector
operator|.
name|getBinding
argument_list|(
name|bindingKey
argument_list|)
decl_stmt|;
if|if
condition|(
name|binding
operator|==
literal|null
condition|)
block|{
name|provider
operator|=
operator|new
name|ListProvider
argument_list|<>
argument_list|()
expr_stmt|;
name|injector
operator|.
name|putBinding
argument_list|(
name|bindingKey
argument_list|,
name|provider
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|provider
operator|=
operator|(
name|ListProvider
argument_list|<
name|T
argument_list|>
operator|)
name|binding
operator|.
name|getOriginal
argument_list|()
expr_stmt|;
block|}
return|return
name|provider
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|in
parameter_list|(
name|Scope
name|scope
parameter_list|)
block|{
name|injector
operator|.
name|changeBindingScope
argument_list|(
name|bindingKey
argument_list|,
name|scope
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

