begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
end_comment

begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    https://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|wocompat
operator|.
name|parser
package|;
end_package

begin_interface
specifier|public
interface|interface
name|ParserConstants
block|{
name|int
name|EOF
init|=
literal|0
decl_stmt|;
name|int
name|INT
init|=
literal|5
decl_stmt|;
name|int
name|FLOAT
init|=
literal|6
decl_stmt|;
name|int
name|STRING
init|=
literal|17
decl_stmt|;
name|int
name|QUOTED_STRING
init|=
literal|30
decl_stmt|;
name|int
name|DEFAULT
init|=
literal|0
decl_stmt|;
name|int
name|WithinComment
init|=
literal|1
decl_stmt|;
name|int
name|WithinQuotedString
init|=
literal|2
decl_stmt|;
name|String
index|[]
name|tokenImage
init|=
block|{
literal|"<EOF>"
block|,
literal|"\" \""
block|,
literal|"\"\\r\""
block|,
literal|"\"\\n\""
block|,
literal|"\"\\t\""
block|,
literal|"<INT>"
block|,
literal|"<FLOAT>"
block|,
literal|"\"=\""
block|,
literal|"\"(\""
block|,
literal|"\")\""
block|,
literal|"\"{\""
block|,
literal|"\"}\""
block|,
literal|"\",\""
block|,
literal|"\";\""
block|,
literal|"\"//\""
block|,
literal|"<token of kind 15>"
block|,
literal|"<token of kind 16>"
block|,
literal|"<STRING>"
block|,
literal|"\"\\\"\""
block|,
literal|"<token of kind 19>"
block|,
literal|"\"\\\\\\\\\""
block|,
literal|"\"\\\\a\""
block|,
literal|"\"\\\\b\""
block|,
literal|"\"\\\\t\""
block|,
literal|"\"\\\\n\""
block|,
literal|"\"\\\\v\""
block|,
literal|"\"\\\\f\""
block|,
literal|"\"\\\\\\\"\""
block|,
literal|"<token of kind 28>"
block|,
literal|"<token of kind 29>"
block|,
literal|"\"\\\"\""
block|,   }
decl_stmt|;
block|}
end_interface

end_unit

