begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|project
operator|.
name|upgrade
operator|.
name|handlers
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|DataChannelDescriptor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|Document
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|Element
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertEquals
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|mockito
operator|.
name|Mockito
operator|.
name|mock
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|mockito
operator|.
name|Mockito
operator|.
name|verifyZeroInteractions
import|;
end_import

begin_comment
comment|/**  * @since 4.1  */
end_comment

begin_class
specifier|public
class|class
name|UpgradeHandler_V9Test
extends|extends
name|BaseUpgradeHandlerTest
block|{
annotation|@
name|Override
name|UpgradeHandler
name|newHandler
parameter_list|()
block|{
return|return
operator|new
name|UpgradeHandler_V9
argument_list|()
return|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testProjectDomUpgrade
parameter_list|()
throws|throws
name|Exception
block|{
name|Document
name|document
init|=
name|processProjectDom
argument_list|(
literal|"cayenne-project-v8.xml"
argument_list|)
decl_stmt|;
name|Element
name|root
init|=
name|document
operator|.
name|getDocumentElement
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|"9"
argument_list|,
name|root
operator|.
name|getAttribute
argument_list|(
literal|"project-version"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|""
argument_list|,
name|root
operator|.
name|getAttribute
argument_list|(
literal|"xmlns"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|root
operator|.
name|getElementsByTagName
argument_list|(
literal|"map"
argument_list|)
operator|.
name|getLength
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testDataMapDomUpgrade
parameter_list|()
throws|throws
name|Exception
block|{
name|Document
name|document
init|=
name|processDataMapDom
argument_list|(
literal|"test-map-v8.map.xml"
argument_list|)
decl_stmt|;
name|Element
name|root
init|=
name|document
operator|.
name|getDocumentElement
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|"9"
argument_list|,
name|root
operator|.
name|getAttribute
argument_list|(
literal|"project-version"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"http://cayenne.apache.org/schema/9/modelMap"
argument_list|,
name|root
operator|.
name|getAttribute
argument_list|(
literal|"xmlns"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|0
argument_list|,
name|root
operator|.
name|getElementsByTagName
argument_list|(
literal|"reverse-engineering-config"
argument_list|)
operator|.
name|getLength
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|root
operator|.
name|getElementsByTagName
argument_list|(
literal|"db-attribute"
argument_list|)
operator|.
name|getLength
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testModelUpgrade
parameter_list|()
throws|throws
name|Exception
block|{
name|DataChannelDescriptor
name|descriptor
init|=
name|mock
argument_list|(
name|DataChannelDescriptor
operator|.
name|class
argument_list|)
decl_stmt|;
name|handler
operator|.
name|processModel
argument_list|(
name|descriptor
argument_list|)
expr_stmt|;
name|verifyZeroInteractions
argument_list|(
name|descriptor
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

