begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|osx
package|;
end_package

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Component
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|Action
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JFrame
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JMenu
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JMenuBar
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JMenuItem
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JPopupMenu
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|di
operator|.
name|Inject
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|action
operator|.
name|AboutAction
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|action
operator|.
name|ActionManager
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|action
operator|.
name|ConfigurePreferencesAction
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|action
operator|.
name|ExitAction
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|init
operator|.
name|platform
operator|.
name|PlatformInitializer
import|;
end_import

begin_import
import|import
name|com
operator|.
name|apple
operator|.
name|eawt
operator|.
name|AboutHandler
import|;
end_import

begin_import
import|import
name|com
operator|.
name|apple
operator|.
name|eawt
operator|.
name|AppEvent
import|;
end_import

begin_import
import|import
name|com
operator|.
name|apple
operator|.
name|eawt
operator|.
name|Application
import|;
end_import

begin_import
import|import
name|com
operator|.
name|apple
operator|.
name|eawt
operator|.
name|PreferencesHandler
import|;
end_import

begin_import
import|import
name|com
operator|.
name|apple
operator|.
name|eawt
operator|.
name|QuitHandler
import|;
end_import

begin_import
import|import
name|com
operator|.
name|apple
operator|.
name|eawt
operator|.
name|QuitResponse
import|;
end_import

begin_class
annotation|@
name|SuppressWarnings
argument_list|(
literal|"deprecation"
argument_list|)
specifier|public
class|class
name|OSXPlatformInitializer
implements|implements
name|PlatformInitializer
block|{
annotation|@
name|Inject
specifier|protected
name|ActionManager
name|actionManager
decl_stmt|;
specifier|public
name|void
name|initLookAndFeel
parameter_list|()
block|{
comment|// leave alone the look and feel. Presumably it is Aqua, since this
comment|// launcher can only be executed on Mac
comment|// configure special Mac menu handlers though...
name|Application
name|app
init|=
name|Application
operator|.
name|getApplication
argument_list|()
decl_stmt|;
name|app
operator|.
name|setAboutHandler
argument_list|(
operator|new
name|AboutHandler
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|void
name|handleAbout
parameter_list|(
name|AppEvent
operator|.
name|AboutEvent
name|aboutEvent
parameter_list|)
block|{
name|actionManager
operator|.
name|getAction
argument_list|(
name|AboutAction
operator|.
name|class
argument_list|)
operator|.
name|showAboutDialog
argument_list|()
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|app
operator|.
name|setPreferencesHandler
argument_list|(
operator|new
name|PreferencesHandler
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|void
name|handlePreferences
parameter_list|(
name|AppEvent
operator|.
name|PreferencesEvent
name|preferencesEvent
parameter_list|)
block|{
name|actionManager
operator|.
name|getAction
argument_list|(
name|ConfigurePreferencesAction
operator|.
name|class
argument_list|)
operator|.
name|showPreferencesDialog
argument_list|()
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|app
operator|.
name|setQuitHandler
argument_list|(
operator|new
name|QuitHandler
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|void
name|handleQuitRequestWith
parameter_list|(
name|AppEvent
operator|.
name|QuitEvent
name|quitEvent
parameter_list|,
name|QuitResponse
name|quitResponse
parameter_list|)
block|{
if|if
condition|(
operator|!
name|actionManager
operator|.
name|getAction
argument_list|(
name|ExitAction
operator|.
name|class
argument_list|)
operator|.
name|exit
argument_list|()
condition|)
block|{
name|quitResponse
operator|.
name|cancelQuit
argument_list|()
expr_stmt|;
block|}
block|}
block|}
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|setupMenus
parameter_list|(
name|JFrame
name|frame
parameter_list|)
block|{
name|Set
argument_list|<
name|Action
argument_list|>
name|removeActions
init|=
operator|new
name|HashSet
argument_list|<>
argument_list|()
decl_stmt|;
name|removeActions
operator|.
name|add
argument_list|(
name|actionManager
operator|.
name|getAction
argument_list|(
name|ExitAction
operator|.
name|class
argument_list|)
argument_list|)
expr_stmt|;
name|removeActions
operator|.
name|add
argument_list|(
name|actionManager
operator|.
name|getAction
argument_list|(
name|AboutAction
operator|.
name|class
argument_list|)
argument_list|)
expr_stmt|;
name|removeActions
operator|.
name|add
argument_list|(
name|actionManager
operator|.
name|getAction
argument_list|(
name|ConfigurePreferencesAction
operator|.
name|class
argument_list|)
argument_list|)
expr_stmt|;
name|JMenuBar
name|menuBar
init|=
name|frame
operator|.
name|getJMenuBar
argument_list|()
decl_stmt|;
for|for
control|(
name|Component
name|menu
range|:
name|menuBar
operator|.
name|getComponents
argument_list|()
control|)
block|{
if|if
condition|(
name|menu
operator|instanceof
name|JMenu
condition|)
block|{
name|JMenu
name|jMenu
init|=
operator|(
name|JMenu
operator|)
name|menu
decl_stmt|;
name|Component
index|[]
name|menuItems
init|=
name|jMenu
operator|.
name|getPopupMenu
argument_list|()
operator|.
name|getComponents
argument_list|()
decl_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|menuItems
operator|.
name|length
condition|;
name|i
operator|++
control|)
block|{
if|if
condition|(
name|menuItems
index|[
name|i
index|]
operator|instanceof
name|JMenuItem
condition|)
block|{
name|JMenuItem
name|jMenuItem
init|=
operator|(
name|JMenuItem
operator|)
name|menuItems
index|[
name|i
index|]
decl_stmt|;
if|if
condition|(
name|removeActions
operator|.
name|contains
argument_list|(
name|jMenuItem
operator|.
name|getAction
argument_list|()
argument_list|)
condition|)
block|{
name|jMenu
operator|.
name|remove
argument_list|(
name|jMenuItem
argument_list|)
expr_stmt|;
comment|// this algorithm is pretty lame, but it works for
comment|// the current (as of 08.2010) menu layout
if|if
condition|(
name|i
operator|>
literal|0
operator|&&
name|i
operator|==
name|menuItems
operator|.
name|length
operator|-
literal|1
operator|&&
name|menuItems
index|[
name|i
operator|-
literal|1
index|]
operator|instanceof
name|JPopupMenu
operator|.
name|Separator
condition|)
block|{
name|jMenu
operator|.
name|remove
argument_list|(
name|i
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
block|}
block|}
block|}
block|}
end_class

end_unit

