begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    https://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|project
operator|.
name|validation
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|DataChannelDescriptor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|DataNodeDescriptor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|configuration
operator|.
name|server
operator|.
name|XMLPoolingDataSourceFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|util
operator|.
name|Util
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|validation
operator|.
name|ValidationResult
import|;
end_import

begin_class
class|class
name|DataNodeValidator
extends|extends
name|ConfigurationNodeValidator
block|{
name|void
name|validate
parameter_list|(
name|DataNodeDescriptor
name|node
parameter_list|,
name|ValidationResult
name|validationResult
parameter_list|)
block|{
name|validateName
argument_list|(
name|node
argument_list|,
name|validationResult
argument_list|)
expr_stmt|;
name|validateConnection
argument_list|(
name|node
argument_list|,
name|validationResult
argument_list|)
expr_stmt|;
block|}
name|void
name|validateConnection
parameter_list|(
name|DataNodeDescriptor
name|node
parameter_list|,
name|ValidationResult
name|validationResult
parameter_list|)
block|{
name|String
name|factory
init|=
name|node
operator|.
name|getDataSourceFactoryType
argument_list|()
decl_stmt|;
comment|// TODO: andrus 03/10/2010 - null factory is allowed, however
comment|// 'getDataSourceDescriptor' must ne not null in this case
if|if
condition|(
name|factory
operator|!=
literal|null
operator|&&
operator|!
name|XMLPoolingDataSourceFactory
operator|.
name|class
operator|.
name|getName
argument_list|()
operator|.
name|equals
argument_list|(
name|factory
argument_list|)
condition|)
block|{
name|String
name|parameters
init|=
name|node
operator|.
name|getParameters
argument_list|()
decl_stmt|;
if|if
condition|(
name|Util
operator|.
name|isEmptyString
argument_list|(
name|parameters
argument_list|)
condition|)
block|{
name|addFailure
argument_list|(
name|validationResult
argument_list|,
name|node
argument_list|,
literal|"DataNode has empty 'parameters' string"
argument_list|)
expr_stmt|;
block|}
block|}
block|}
name|void
name|validateName
parameter_list|(
name|DataNodeDescriptor
name|node
parameter_list|,
name|ValidationResult
name|validationResult
parameter_list|)
block|{
name|String
name|name
init|=
name|node
operator|.
name|getName
argument_list|()
decl_stmt|;
if|if
condition|(
name|Util
operator|.
name|isEmptyString
argument_list|(
name|name
argument_list|)
condition|)
block|{
name|addFailure
argument_list|(
name|validationResult
argument_list|,
name|node
argument_list|,
literal|"Unnamed DataNode"
argument_list|)
expr_stmt|;
return|return;
block|}
name|DataChannelDescriptor
name|dataChannelDescriptor
init|=
name|node
operator|.
name|getDataChannelDescriptor
argument_list|()
decl_stmt|;
comment|// check for duplicate names in the parent context
for|for
control|(
name|DataNodeDescriptor
name|otherNode
range|:
name|dataChannelDescriptor
operator|.
name|getNodeDescriptors
argument_list|()
control|)
block|{
if|if
condition|(
name|otherNode
operator|==
name|node
condition|)
block|{
continue|continue;
block|}
if|if
condition|(
name|name
operator|.
name|equals
argument_list|(
name|otherNode
operator|.
name|getName
argument_list|()
argument_list|)
condition|)
block|{
name|addFailure
argument_list|(
name|validationResult
argument_list|,
name|node
argument_list|,
literal|"Duplicate DataNode name: %s"
argument_list|,
name|name
argument_list|)
expr_stmt|;
break|break;
block|}
block|}
block|}
block|}
end_class

end_unit

