begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|dialog
operator|.
name|validator
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JFrame
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|access
operator|.
name|DataDomain
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|ProjectController
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|project
operator|.
name|validator
operator|.
name|ValidationInfo
import|;
end_import

begin_comment
comment|/**  * JUnit tests for ValidationDisplayHandler class.  *   * @author Andrus Adamchik  */
end_comment

begin_class
specifier|public
class|class
name|ValidationDisplayHandlerTest
extends|extends
name|TestCase
block|{
specifier|public
name|void
name|testValidationInfo
parameter_list|()
throws|throws
name|Exception
block|{
name|ValidationInfo
name|info
init|=
operator|new
name|ValidationInfo
argument_list|(
operator|-
literal|1
argument_list|,
literal|"123"
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|ValidationDisplayHandler
name|handler
init|=
operator|new
name|ConcreteErrorMsg
argument_list|(
name|info
argument_list|)
decl_stmt|;
name|assertSame
argument_list|(
name|info
argument_list|,
name|handler
operator|.
name|getValidationInfo
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testMessage
parameter_list|()
throws|throws
name|Exception
block|{
name|String
name|msg
init|=
literal|"abc"
decl_stmt|;
name|ValidationInfo
name|info
init|=
operator|new
name|ValidationInfo
argument_list|(
operator|-
literal|1
argument_list|,
name|msg
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|ValidationDisplayHandler
name|handler
init|=
operator|new
name|ConcreteErrorMsg
argument_list|(
name|info
argument_list|)
decl_stmt|;
name|assertSame
argument_list|(
name|msg
argument_list|,
name|handler
operator|.
name|getMessage
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testSeverity
parameter_list|()
throws|throws
name|Exception
block|{
name|ValidationInfo
name|info
init|=
operator|new
name|ValidationInfo
argument_list|(
name|ValidationDisplayHandler
operator|.
name|ERROR
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|ValidationDisplayHandler
name|handler
init|=
operator|new
name|ConcreteErrorMsg
argument_list|(
name|info
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|ValidationDisplayHandler
operator|.
name|ERROR
argument_list|,
name|handler
operator|.
name|getSeverity
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testDomain
parameter_list|()
throws|throws
name|Exception
block|{
name|ValidationInfo
name|info
init|=
operator|new
name|ValidationInfo
argument_list|(
name|ValidationDisplayHandler
operator|.
name|ERROR
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|ValidationDisplayHandler
name|handler
init|=
operator|new
name|ConcreteErrorMsg
argument_list|(
name|info
argument_list|)
decl_stmt|;
name|DataDomain
name|dom
init|=
operator|new
name|DataDomain
argument_list|(
literal|"test"
argument_list|)
decl_stmt|;
name|assertNull
argument_list|(
name|handler
operator|.
name|getDomain
argument_list|()
argument_list|)
expr_stmt|;
name|handler
operator|.
name|setDomain
argument_list|(
name|dom
argument_list|)
expr_stmt|;
name|assertSame
argument_list|(
name|dom
argument_list|,
name|handler
operator|.
name|getDomain
argument_list|()
argument_list|)
expr_stmt|;
block|}
class|class
name|ConcreteErrorMsg
extends|extends
name|ValidationDisplayHandler
block|{
comment|/**          * Constructor for ConcreteErrorMsg.          * @param validation          */
specifier|public
name|ConcreteErrorMsg
parameter_list|(
name|ValidationInfo
name|validation
parameter_list|)
block|{
name|super
argument_list|(
name|validation
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|displayField
parameter_list|(
name|ProjectController
name|mediator
parameter_list|,
name|JFrame
name|frame
parameter_list|)
block|{
block|}
block|}
block|}
end_class

end_unit

