begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|jpa
operator|.
name|reflect
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|Fault
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|ValueHolder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|reflect
operator|.
name|Accessor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|reflect
operator|.
name|ClassDescriptor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|reflect
operator|.
name|ListProperty
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|reflect
operator|.
name|PropertyException
import|;
end_import

begin_comment
comment|// TODO: andrus 11/25/2006 - this should be modeled after EnhancedPojo instead of
end_comment

begin_comment
comment|// DataObject to-many property.
end_comment

begin_class
class|class
name|JpaToManyProperty
extends|extends
name|ListProperty
block|{
specifier|public
name|JpaToManyProperty
parameter_list|(
name|ClassDescriptor
name|owner
parameter_list|,
name|ClassDescriptor
name|targetDescriptor
parameter_list|,
name|Accessor
name|accessor
parameter_list|,
name|String
name|reverseName
parameter_list|)
block|{
name|super
argument_list|(
name|owner
argument_list|,
name|targetDescriptor
argument_list|,
name|accessor
argument_list|,
name|reverseName
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|writePropertyDirectly
parameter_list|(
name|Object
name|object
parameter_list|,
name|Object
name|oldValue
parameter_list|,
name|Object
name|newValue
parameter_list|)
throws|throws
name|PropertyException
block|{
name|accessor
operator|.
name|setValue
argument_list|(
name|object
argument_list|,
name|newValue
argument_list|)
expr_stmt|;
block|}
comment|/**      * Overrides super to replace user-provided Collections with Cayenne-enabled      * collections.      */
annotation|@
name|Override
specifier|protected
name|ValueHolder
name|ensureCollectionValueHolderSet
parameter_list|(
name|Object
name|object
parameter_list|)
throws|throws
name|PropertyException
block|{
name|Object
name|value
init|=
name|accessor
operator|.
name|getValue
argument_list|(
name|object
argument_list|)
decl_stmt|;
if|if
condition|(
name|value
operator|==
literal|null
operator|||
name|value
operator|instanceof
name|Fault
condition|)
block|{
name|value
operator|=
name|createCollectionValueHolder
argument_list|(
name|object
argument_list|)
expr_stmt|;
name|accessor
operator|.
name|setValue
argument_list|(
name|object
argument_list|,
name|value
argument_list|)
expr_stmt|;
block|}
if|else if
condition|(
operator|!
operator|(
name|value
operator|instanceof
name|ValueHolder
operator|)
condition|)
block|{
if|if
condition|(
name|value
operator|instanceof
name|Collection
operator|||
name|value
operator|instanceof
name|Map
condition|)
block|{
name|ValueHolder
name|valueHolder
init|=
name|createCollectionValueHolder
argument_list|(
name|object
argument_list|)
decl_stmt|;
name|valueHolder
operator|.
name|setValueDirectly
argument_list|(
name|value
argument_list|)
expr_stmt|;
name|accessor
operator|.
name|setValue
argument_list|(
name|object
argument_list|,
name|valueHolder
argument_list|)
expr_stmt|;
name|value
operator|=
name|valueHolder
expr_stmt|;
block|}
block|}
return|return
operator|(
name|ValueHolder
operator|)
name|value
return|;
block|}
block|}
end_class

end_unit

