begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|access
operator|.
name|jdbc
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|CayenneException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|access
operator|.
name|ResultIterator
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|DbEntity
import|;
end_import

begin_class
specifier|public
class|class
name|LimitResultIterator
implements|implements
name|ResultIterator
block|{
specifier|protected
name|ResultIterator
name|wrappedIterator
decl_stmt|;
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|nextDataObjectIds
decl_stmt|;
specifier|protected
name|int
name|fetchLimit
decl_stmt|;
specifier|protected
name|int
name|fetchedSoFar
decl_stmt|;
specifier|protected
name|boolean
name|nextRow
decl_stmt|;
specifier|public
name|LimitResultIterator
parameter_list|(
name|ResultIterator
name|wrappedIterator
parameter_list|,
name|int
name|fetchLimit
parameter_list|)
throws|throws
name|CayenneException
block|{
if|if
condition|(
name|wrappedIterator
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|CayenneException
argument_list|(
literal|"Null wrapped iterator."
argument_list|)
throw|;
block|}
name|this
operator|.
name|wrappedIterator
operator|=
name|wrappedIterator
expr_stmt|;
name|this
operator|.
name|fetchLimit
operator|=
name|fetchLimit
expr_stmt|;
name|checkNextRow
argument_list|()
expr_stmt|;
block|}
specifier|private
name|void
name|checkNextRow
parameter_list|()
throws|throws
name|CayenneException
block|{
name|nextRow
operator|=
literal|false
expr_stmt|;
if|if
condition|(
operator|(
name|fetchLimit
operator|<=
literal|0
operator|||
name|fetchedSoFar
operator|<
name|fetchLimit
operator|)
operator|&&
name|this
operator|.
name|wrappedIterator
operator|.
name|hasNextRow
argument_list|()
condition|)
block|{
name|nextRow
operator|=
literal|true
expr_stmt|;
name|fetchedSoFar
operator|++
expr_stmt|;
block|}
block|}
specifier|protected
name|Map
name|readDataRow
parameter_list|()
throws|throws
name|CayenneException
block|{
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|next
init|=
name|wrappedIterator
operator|.
name|nextDataRow
argument_list|()
decl_stmt|;
return|return
name|next
return|;
block|}
specifier|public
name|void
name|close
parameter_list|()
throws|throws
name|CayenneException
block|{
name|wrappedIterator
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
specifier|public
name|List
name|dataRows
parameter_list|(
name|boolean
name|close
parameter_list|)
throws|throws
name|CayenneException
block|{
name|List
argument_list|<
name|Map
argument_list|>
name|list
init|=
operator|new
name|ArrayList
argument_list|<
name|Map
argument_list|>
argument_list|()
decl_stmt|;
try|try
block|{
while|while
condition|(
name|this
operator|.
name|hasNextRow
argument_list|()
condition|)
block|{
name|list
operator|.
name|add
argument_list|(
name|this
operator|.
name|nextDataRow
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|list
return|;
block|}
finally|finally
block|{
if|if
condition|(
name|close
condition|)
block|{
name|close
argument_list|()
expr_stmt|;
block|}
block|}
block|}
specifier|public
name|int
name|getDataRowWidth
parameter_list|()
block|{
return|return
name|wrappedIterator
operator|.
name|getDataRowWidth
argument_list|()
return|;
block|}
specifier|public
name|boolean
name|hasNextRow
parameter_list|()
throws|throws
name|CayenneException
block|{
return|return
name|nextRow
return|;
block|}
specifier|public
name|Map
name|nextDataRow
parameter_list|()
throws|throws
name|CayenneException
block|{
if|if
condition|(
operator|!
name|hasNextRow
argument_list|()
condition|)
block|{
throw|throw
operator|new
name|CayenneException
argument_list|(
literal|"An attempt to read uninitialized row or past the end of the iterator."
argument_list|)
throw|;
block|}
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|row
init|=
name|readDataRow
argument_list|()
decl_stmt|;
name|checkNextRow
argument_list|()
expr_stmt|;
return|return
name|row
return|;
block|}
specifier|public
name|Object
name|nextId
parameter_list|(
name|DbEntity
name|entity
parameter_list|)
throws|throws
name|CayenneException
block|{
if|if
condition|(
operator|!
name|hasNextRow
argument_list|()
condition|)
block|{
throw|throw
operator|new
name|CayenneException
argument_list|(
literal|"An attempt to read uninitialized row or past the end of the iterator."
argument_list|)
throw|;
block|}
name|Object
name|id
init|=
name|readId
argument_list|(
name|entity
argument_list|)
decl_stmt|;
name|checkNextId
argument_list|(
name|entity
argument_list|)
expr_stmt|;
return|return
name|id
return|;
block|}
specifier|public
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|nextObjectId
parameter_list|(
name|DbEntity
name|entity
parameter_list|)
throws|throws
name|CayenneException
block|{
if|if
condition|(
operator|!
name|hasNextRow
argument_list|()
condition|)
block|{
throw|throw
operator|new
name|CayenneException
argument_list|(
literal|"An attempt to read uninitialized row or past the end of the iterator."
argument_list|)
throw|;
block|}
name|checkNextObjectId
argument_list|(
name|entity
argument_list|)
expr_stmt|;
return|return
name|nextDataObjectIds
return|;
block|}
specifier|public
name|void
name|skipDataRow
parameter_list|()
throws|throws
name|CayenneException
block|{
name|wrappedIterator
operator|.
name|skipDataRow
argument_list|()
expr_stmt|;
block|}
name|void
name|checkNextId
parameter_list|(
name|DbEntity
name|entity
parameter_list|)
throws|throws
name|CayenneException
block|{
if|if
condition|(
name|entity
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|CayenneException
argument_list|(
literal|"Null DbEntity, can't create id."
argument_list|)
throw|;
block|}
name|nextRow
operator|=
literal|false
expr_stmt|;
if|if
condition|(
name|wrappedIterator
operator|.
name|hasNextRow
argument_list|()
condition|)
block|{
name|nextRow
operator|=
literal|true
expr_stmt|;
block|}
block|}
specifier|public
name|Object
name|readId
parameter_list|(
name|DbEntity
name|entity
parameter_list|)
throws|throws
name|CayenneException
block|{
name|Object
name|next
init|=
name|wrappedIterator
operator|.
name|nextId
argument_list|(
name|entity
argument_list|)
decl_stmt|;
return|return
name|next
return|;
block|}
name|void
name|checkNextObjectId
parameter_list|(
name|DbEntity
name|entity
parameter_list|)
throws|throws
name|CayenneException
block|{
if|if
condition|(
name|entity
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|CayenneException
argument_list|(
literal|"Null DbEntity, can't create id."
argument_list|)
throw|;
block|}
name|nextRow
operator|=
literal|false
expr_stmt|;
name|nextDataObjectIds
operator|=
literal|null
expr_stmt|;
if|if
condition|(
name|wrappedIterator
operator|.
name|hasNextRow
argument_list|()
condition|)
block|{
name|nextRow
operator|=
literal|true
expr_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|next
init|=
name|wrappedIterator
operator|.
name|nextObjectId
argument_list|(
name|entity
argument_list|)
decl_stmt|;
name|nextDataObjectIds
operator|=
name|next
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

