begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    https://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|dbsync
operator|.
name|reverse
operator|.
name|dbload
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|DbAttribute
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|DbEntity
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|DbRelationship
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|ObjAttribute
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|ObjEntity
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|ObjRelationship
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|map
operator|.
name|Procedure
import|;
end_import

begin_comment
comment|/**  * @since 4.0  */
end_comment

begin_class
specifier|public
class|class
name|ProxyModelMergeDelegate
implements|implements
name|ModelMergeDelegate
block|{
specifier|private
specifier|final
name|ModelMergeDelegate
name|delegate
decl_stmt|;
specifier|public
name|ProxyModelMergeDelegate
parameter_list|(
name|ModelMergeDelegate
name|delegate
parameter_list|)
block|{
name|this
operator|.
name|delegate
operator|=
name|delegate
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|dbEntityAdded
parameter_list|(
name|DbEntity
name|ent
parameter_list|)
block|{
name|delegate
operator|.
name|dbEntityAdded
argument_list|(
name|ent
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|dbEntityRemoved
parameter_list|(
name|DbEntity
name|ent
parameter_list|)
block|{
name|delegate
operator|.
name|dbEntityRemoved
argument_list|(
name|ent
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|objEntityAdded
parameter_list|(
name|ObjEntity
name|ent
parameter_list|)
block|{
name|delegate
operator|.
name|objEntityAdded
argument_list|(
name|ent
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|objEntityRemoved
parameter_list|(
name|ObjEntity
name|ent
parameter_list|)
block|{
name|delegate
operator|.
name|objEntityRemoved
argument_list|(
name|ent
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|dbAttributeAdded
parameter_list|(
name|DbAttribute
name|att
parameter_list|)
block|{
name|delegate
operator|.
name|dbAttributeAdded
argument_list|(
name|att
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|dbAttributeRemoved
parameter_list|(
name|DbAttribute
name|att
parameter_list|)
block|{
name|delegate
operator|.
name|dbAttributeRemoved
argument_list|(
name|att
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|dbAttributeModified
parameter_list|(
name|DbAttribute
name|att
parameter_list|)
block|{
name|delegate
operator|.
name|dbAttributeModified
argument_list|(
name|att
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|objAttributeAdded
parameter_list|(
name|ObjAttribute
name|att
parameter_list|)
block|{
name|delegate
operator|.
name|objAttributeAdded
argument_list|(
name|att
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|objAttributeRemoved
parameter_list|(
name|ObjAttribute
name|att
parameter_list|)
block|{
name|delegate
operator|.
name|objAttributeRemoved
argument_list|(
name|att
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|objAttributeModified
parameter_list|(
name|ObjAttribute
name|att
parameter_list|)
block|{
name|delegate
operator|.
name|objAttributeModified
argument_list|(
name|att
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|dbRelationshipAdded
parameter_list|(
name|DbRelationship
name|rel
parameter_list|)
block|{
name|delegate
operator|.
name|dbRelationshipAdded
argument_list|(
name|rel
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|dbRelationshipRemoved
parameter_list|(
name|DbRelationship
name|rel
parameter_list|)
block|{
name|delegate
operator|.
name|dbRelationshipRemoved
argument_list|(
name|rel
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|objRelationshipAdded
parameter_list|(
name|ObjRelationship
name|rel
parameter_list|)
block|{
name|delegate
operator|.
name|objRelationshipAdded
argument_list|(
name|rel
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|objRelationshipRemoved
parameter_list|(
name|ObjRelationship
name|rel
parameter_list|)
block|{
name|delegate
operator|.
name|objRelationshipRemoved
argument_list|(
name|rel
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|procedureAdded
parameter_list|(
name|Procedure
name|procedure
parameter_list|)
block|{
name|delegate
operator|.
name|procedureAdded
argument_list|(
name|procedure
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|procedureRemoved
parameter_list|(
name|Procedure
name|procedure
parameter_list|)
block|{
name|delegate
operator|.
name|procedureRemoved
argument_list|(
name|procedure
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

