begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    https://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|modeler
operator|.
name|util
operator|.
name|path
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_class
specifier|public
class|class
name|DefaultResourceTrimmer
implements|implements
name|PathTrimmer
block|{
specifier|private
specifier|static
name|String
name|DEFAULT_RESOURCE_PATH
decl_stmt|;
specifier|private
specifier|static
name|String
name|DEFAULT_TEST_RESOURCE_PATH
decl_stmt|;
static|static
block|{
name|String
name|separator
init|=
name|File
operator|.
name|separator
decl_stmt|;
name|DEFAULT_RESOURCE_PATH
operator|=
literal|"src"
operator|+
name|separator
operator|+
literal|"main"
operator|+
name|separator
operator|+
literal|"resources"
expr_stmt|;
name|DEFAULT_TEST_RESOURCE_PATH
operator|=
literal|"src"
operator|+
name|separator
operator|+
literal|"test"
operator|+
name|separator
operator|+
literal|"resources"
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|trim
parameter_list|(
name|String
name|path
parameter_list|)
block|{
name|path
operator|=
name|path
operator|.
name|replace
argument_list|(
name|DEFAULT_TEST_RESOURCE_PATH
argument_list|,
literal|"..test.."
argument_list|)
expr_stmt|;
name|path
operator|=
name|path
operator|.
name|replace
argument_list|(
name|DEFAULT_RESOURCE_PATH
argument_list|,
literal|"..main.."
argument_list|)
expr_stmt|;
return|return
name|path
return|;
block|}
block|}
end_class

end_unit

