begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************  *   Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *    https://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing,  *  software distributed under the License is distributed on an  *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  *  KIND, either express or implied.  See the License for the  *  specific language governing permissions and limitations  *  under the License.  ****************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|access
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|DataRow
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|cayenne
operator|.
name|Persistent
import|;
end_import

begin_class
class|class
name|StackLookupParentAttachmentStrategy
implements|implements
name|ParentAttachmentStrategy
block|{
specifier|private
specifier|final
name|PrefetchProcessorNode
name|node
decl_stmt|;
name|StackLookupParentAttachmentStrategy
parameter_list|(
name|PrefetchProcessorNode
name|node
parameter_list|)
block|{
name|this
operator|.
name|node
operator|=
name|node
expr_stmt|;
block|}
specifier|public
name|void
name|linkToParent
parameter_list|(
name|DataRow
name|row
parameter_list|,
name|Persistent
name|object
parameter_list|)
block|{
name|PrefetchProcessorNode
name|parent
init|=
operator|(
name|PrefetchProcessorNode
operator|)
name|node
operator|.
name|getParent
argument_list|()
decl_stmt|;
name|node
operator|.
name|linkToParent
argument_list|(
name|object
argument_list|,
name|parent
operator|.
name|getLastResolved
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

